BatchedNetworkPeer::BatchedNetworkPeer(std::shared_ptr<NetworkPeer>, Scheduler&)
BatchedNetworkPeer::~BatchedNetworkPeer()
BatchedNetworkPeer::~BatchedNetworkPeer()
BatchedNetworkPeer::setAsyncEnabled(bool)
BatchedNetworkPeer::getCompressibleState(unsigned long) const
BatchedNetworkPeer::flush(std::function<void ()>&&)
BatchedNetworkPeer::_startSendTask()
BatchedNetworkPeer::update()
BatchedNetworkPeer::sendPacket(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, NetworkPeer::Reliability, int, unsigned short, Compressibility)
BatchedNetworkPeer::receivePacket(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
BatchedNetworkPeer::getNetworkStatus()
