ClassroomModeNetworkHandler::ClassroomModeNetworkHandler(bool)
ClassroomModeNetworkHandler::~ClassroomModeNetworkHandler()
ClassroomModeNetworkHandler::~ClassroomModeNetworkHandler()
ClassroomModeNetworkHandler::allowIncomingPacketId(NetworkIdentifier const&, MinecraftPacketIds)
ClassroomModeNetworkHandler::onWebsocketRequest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>)
ClassroomModeNetworkHandler::_connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
