LocalConnectivitySystem::getHost() const
LocalConnectivitySystem::addHost(LocalConnector&)
LocalConnectivitySystem::removeHost(LocalConnector&)
LocalNetworkPeer::LocalNetworkPeer()
LocalNetworkPeer::setOtherPeer(std::weak_ptr<LocalNetworkPeer>)
LocalNetworkPeer::sendPacket(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, NetworkPeer::Reliability, int, unsigned short, Compressibility)
LocalNetworkPeer::addIncomingData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
LocalNetworkPeer::receivePacket(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
LocalNetworkPeer::getNetworkStatus()
LocalConnector::LocalConnector(LocalConnector::ConnectionCallbacks&, NetworkIdentifier const&)
LocalConnector::~LocalConnector()
LocalConnector::disconnect()
LocalConnector::~LocalConnector()
LocalConnector::host(NetworkIdentifier const&)
LocalConnector::connect(NetworkIdentifier const&)
LocalConnector::createPeer(LocalConnector&)
LocalConnector::onRemoteDisconnected(LocalConnector const&)
LocalConnector::runEvents()
LocalConnector::getGUID() const
