LoopbackPacketSender::LoopbackPacketSender(unsigned char, NetworkHandler&)
LoopbackPacketSender::addLoopbackCallback(NetEventCallback&)
LoopbackPacketSender::removeLoopbackCallback(NetEventCallback&)
LoopbackPacketSender::setUserList(std::vector<std::unique_ptr<Player, std::default_delete<Player> >, std::allocator<std::unique_ptr<Player, std::default_delete<Player> > > > const*)
LoopbackPacketSender::send(Packet&)
LoopbackPacketSender::sendToClient(NetworkIdentifier const&, Packet const&, unsigned char)
LoopbackPacketSender::sendToClients(std::vector<NetworkIdentifierWithSubId, std::allocator<NetworkIdentifierWithSubId> > const&, Packet const&)
LoopbackPacketSender::sendToServer(Packet&)
LoopbackPacketSender::sendBroadcast(Packet const&)
LoopbackPacketSender::sendBroadcast(NetworkIdentifier const&, unsigned char, Packet const&)
LoopbackPacketSender::flush(NetworkIdentifier const&, std::function<void ()>&&)
