RakNetServerLocator::PingRateRecorder::PingRateRecorder(unsigned int, bool)
RakNetServerLocator::PingRateRecorder::_updateAverage(float)
RakNetServerLocator::PingRateRecorder::pingStart(unsigned int const&, int)
RakNetServerLocator::PingRateRecorder::pingEnd(unsigned int const&, int)
RakNetServerLocator::PingRateRecorder::getLastPingTime() const
RakNetServerLocator::PingRateRecorder::getAverageLatency() const
RakNetServerLocator::RakNetServerLocator(RakNetInstance&, RakPeerHelper::IPSupportInterface&, bool)
RakNetServerLocator::~RakNetServerLocator()
RakNetServerLocator::~RakNetServerLocator()
RakNetServerLocator::_updateQueuedPings()
RakNetServerLocator::_addCustomServerFromIpResolver(AsynchronousIPResolver const&, int)
RakNetServerLocator::update()
RakNetServerLocator::handleUnconnectedPong(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RakNet::Packet const*, bool, unsigned long)
RakNetServerLocator::_pingServerV4(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
RakNetServerLocator::_pingServerV6(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
RakNetServerLocator::announceServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GameType, int, int, bool)
RakNetServerLocator::activate()
RakNetServerLocator::stopAnnouncingServer()
RakNetServerLocator::findServers(int, int)
RakNetServerLocator::addCustomServer(AsynchronousIPResolver const&, int)
RakNetServerLocator::addCustomServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
RakNetServerLocator::_addCustomServerV4(AsynchronousIPResolver const&, int)
RakNetServerLocator::_addCustomServerV6(AsynchronousIPResolver const&, int)
RakNetServerLocator::_getHostGuid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
RakNetServerLocator::_onPingSend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
RakNetServerLocator::stopFindingServers()
RakNetServerLocator::getServerList() const
RakNetServerLocator::clearServerList()
RakNetServerLocator::isIPv4Supported() const
RakNetServerLocator::isIPv6Supported() const
RakNetServerLocator::setHostGUID(std::function<RakNet::RakNetGUID ()>)
RakNetServerLocator::getPingTimeForGUID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
RakNetServerLocator::checkCanConnectToCustomServerAsync(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::function<void (bool)>)
RakNetServerLocator::_getServerOriginalAddress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
RakNetServerLocator::_onPongReceive(float&, RakNet::RakNetGUID const&, unsigned int const&, int)
RakNetServerLocator::_validateServerVersion(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
