DefaultDataLoadHelper::loadPosition(Vec3 const&)
DefaultDataLoadHelper::loadBlockPosition(BlockPos const&)
DefaultDataLoadHelper::loadBlockPositionOffset(BlockPos const&)
DefaultDataLoadHelper::loadRotationDegreesX(float)
DefaultDataLoadHelper::loadRotationDegreesY(float)
DefaultDataLoadHelper::loadRotationRadiansX(float)
DefaultDataLoadHelper::loadRotationRadiansY(float)
DefaultDataLoadHelper::loadFacingID(unsigned char)
DefaultDataLoadHelper::loadDirection(Vec3 const&)
DefaultDataLoadHelper::loadDirection(Direction::Type)
DefaultDataLoadHelper::loadRotation(Rotation)
DefaultDataLoadHelper::loadMirror(Mirror)
DefaultDataLoadHelper::loadActorUniqueID(ActorUniqueID)
DefaultDataLoadHelper::loadOwnerID(ActorUniqueID)
DefaultDataLoadHelper::getType() const
DefaultDataLoadHelper::shouldResetTime()
