ServerScoreboard::ServerScoreboard(ServerScoreboard::unit_test_ctor_t)
ServerScoreboard::ServerScoreboard(CommandSoftEnumRegistry, LevelStorage*)
ServerScoreboard::_readFromLevelStorage()
ServerScoreboard::onObjectiveAdded(Objective const&)
ServerScoreboard::_setDirty(bool)
ServerScoreboard::onObjectiveRemoved(Objective&)
ServerScoreboard::isTrackingObjective(Objective const&) const
ServerScoreboard::_notifyClearDisplayObjectiveCallback(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DisplayObjective const&)
ServerScoreboard::_stopTrackingObjective(Objective const&)
ServerScoreboard::_broadcast(Packet const&)
ServerScoreboard::onScoreChanged(ScoreboardId const&, Objective const&)
ServerScoreboard::_notifyScoreChangedCallback(ScoreboardId const&)
ServerScoreboard::onPlayerScoreRemoved(ScoreboardId const&, Objective const&)
ServerScoreboard::_notifyScoreRemovedCallback(ScoreboardId const&)
ServerScoreboard::onPlayerIdentityUpdated(PlayerScoreboardId const&)
ServerScoreboard::_notifyIdentityUpdatedCallback(ScoreboardId const&)
ServerScoreboard::setPacketSender(PacketSender*)
ServerScoreboard::setDisplayObjective(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Objective const&, ObjectiveSortOrder)
ServerScoreboard::_notifySetDisplayObjectiveCallback(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DisplayObjective const&)
ServerScoreboard::_startTrackingObjective(Objective const&)
ServerScoreboard::_unpackIdentityDefToScorePacket(ScoreboardIdentityRef const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
ServerScoreboard::clearDisplayObjective(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ServerScoreboard::onPlayerJoined(Player const&)
ServerScoreboard::_sendTo(NetworkIdentifier const&, unsigned char, Packet const&)
ServerScoreboard::tick()
ServerScoreboard::_isDirty() const
ServerScoreboard::createScoreboardId(Player const&)
ServerScoreboard::_getNewScoreboardId()
ServerScoreboard::createScoreboardId(Actor const&)
ServerScoreboard::createScoreboardId(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ServerScoreboard::serialize() const
ServerScoreboard::deserialize(std::unique_ptr<CompoundTag, std::default_delete<CompoundTag> >)
ServerScoreboard::setScoreChangedCallback(std::function<void (ScoreboardId const&)>)
ServerScoreboard::setScoreRemovedCallback(std::function<void (ScoreboardId const&)>)
ServerScoreboard::setSetDisplayObjectiveCallback(std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DisplayObjective const&)>)
ServerScoreboard::setClearDisplayObjectiveCallback(std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DisplayObjective const&)>)
ServerScoreboard::setIdentityUpdatedCallback(std::function<void (ScoreboardId const&)>)
ServerScoreboard::isClientSide() const
ServerScoreboard::writeToLevelStorage()
