AnvilContainerManagerModel::AnvilContainerManagerModel(ContainerID, Player&, BlockPos const&)
AnvilContainerManagerModel::~AnvilContainerManagerModel()
AnvilContainerManagerModel::~AnvilContainerManagerModel()
AnvilContainerManagerModel::init()
AnvilContainerManagerModel::getItems()
AnvilContainerManagerModel::setSlot(int, ContainerItemStack const&, bool)
AnvilContainerManagerModel::getSlot(int)
AnvilContainerManagerModel::setData(int, int)
AnvilContainerManagerModel::broadcastChanges()
AnvilContainerManagerModel::isAnvilValid(float)
AnvilContainerManagerModel::applyDamageToAnvilBlock()
AnvilContainerManagerModel::fireItemCraftedEvent(ItemInstance const&)
AnvilContainerManagerModel::fireItemAcquiredEvent(ItemInstance const&, int)
AnvilContainerManagerModel::sendCraftedPacket(CraftingEventPacket&)
AnvilContainerManagerModel::getBlockPos() const
