MaterialReducerContainerManagerModel::MaterialReducerContainerManagerModel(ContainerID, Player&, BlockPos const&)
MaterialReducerContainerManagerModel::init()
MaterialReducerContainerManagerModel::getItems()
MaterialReducerContainerManagerModel::setSlot(int, ContainerItemStack const&, bool)
MaterialReducerContainerManagerModel::getSlot(int)
MaterialReducerContainerManagerModel::setData(int, int)
MaterialReducerContainerManagerModel::broadcastChanges()
MaterialReducerContainerManagerModel::isValid(float)
MaterialReducerContainerManagerModel::setInput(ItemStack const&)
MaterialReducerContainerManagerModel::getInput()
MaterialReducerContainerManagerModel::setOutput(int, ContainerItemStack const&)
MaterialReducerContainerManagerModel::getOutput(int)
