Facing::toString(unsigned char)
Facing::getRandomFace(Random&)
Facing::getRandomFaceHorizontal(Random&)
Facing::from2DDataValue(int)
Facing::getClockWise(unsigned char)
Facing::getCounterClockWise(unsigned char)
Facing::getOpposite(unsigned char)
Facing::rotateFace(unsigned char, Facing::Rotation)
Facing::fromVec3(Vec3 const&)
Facing::convertWeirdoDirectionToFacingDirection(WeirdoDirection)
Facing::convertYRotationToFacingDirection(float)
