ItemFrameBlockActor::ItemFrameBlockActor(BlockPos)
ItemFrameBlockActor::ItemFrameBlockActor(BlockPos, BlockActorType)
ItemFrameBlockActor::tick(BlockSource&)
ItemFrameBlockActor::_updateMapBit(BlockSource&)
ItemFrameBlockActor::load(Level&, CompoundTag const&, DataLoadHelper&)
ItemFrameBlockActor::updateNameTag()
ItemFrameBlockActor::save(CompoundTag&) const
ItemFrameBlockActor::getClockFrame()
ItemFrameBlockActor::getCompassFrame()
ItemFrameBlockActor::getFramedItem()
ItemFrameBlockActor::getShadowRadius(BlockSource&) const
ItemFrameBlockActor::getRotation()
ItemFrameBlockActor::rotateFramedItem()
ItemFrameBlockActor::dropFramedItem(BlockSource&, bool)
ItemFrameBlockActor::_checkMapRemoval(BlockSource&, ItemInstance&)
ItemFrameBlockActor::actuallyDropItem(BlockSource&, bool)
ItemFrameBlockActor::setItem(BlockSource&, ItemInstance const&)
ItemFrameBlockActor::onChanged(BlockSource&)
ItemFrameBlockActor::getUpdatePacket(BlockSource&)
ItemFrameBlockActor::_onUpdatePacket(CompoundTag const&, BlockSource&)
