MobSpawnerBlockActor::MobSpawnerBlockActor(BlockPos const&)
MobSpawnerBlockActor::load(Level&, CompoundTag const&, DataLoadHelper&)
MobSpawnerBlockActor::save(CompoundTag&) const
MobSpawnerBlockActor::tick(BlockSource&)
MobSpawnerBlockActor::getUpdatePacket(BlockSource&)
MobSpawnerBlockActor::_onUpdatePacket(CompoundTag const&, BlockSource&)
MobSpawnerBlockActor::getSpawner()
DefaultMobSpawner::DefaultMobSpawner(MobSpawnerBlockActor*)
DefaultMobSpawner::~DefaultMobSpawner()
DefaultMobSpawner::~DefaultMobSpawner()
DefaultMobSpawner::getPos()
