RakNet::BitStream::GetInstance()
RakNet::BitStream::DestroyInstance(RakNet::BitStream*)
RakNet::BitStream::BitStream()
RakNet::BitStream::BitStream(unsigned int)
RakNet::BitStream::BitStream(unsigned char*, unsigned int, bool)
RakNet::BitStream::SetNumberOfBitsAllocated(unsigned int)
RakNet::BitStream::~BitStream()
RakNet::BitStream::Reset()
RakNet::BitStream::Write(char const*, unsigned int)
RakNet::BitStream::AddBitsAndReallocate(unsigned int)
RakNet::BitStream::WriteBits(unsigned char const*, unsigned int, bool)
RakNet::BitStream::Write(RakNet::BitStream*)
RakNet::BitStream::Write(RakNet::BitStream*, unsigned int)
RakNet::BitStream::Write(RakNet::BitStream&, unsigned int)
RakNet::BitStream::Write(RakNet::BitStream&)
RakNet::BitStream::Read(RakNet::BitStream*, unsigned int)
RakNet::BitStream::Read(RakNet::BitStream*)
RakNet::BitStream::Read(RakNet::BitStream&, unsigned int)
RakNet::BitStream::Read(RakNet::BitStream&)
RakNet::BitStream::Read(char*, unsigned int)
RakNet::BitStream::ReadBits(unsigned char*, unsigned int, bool)
RakNet::BitStream::ResetReadPointer()
RakNet::BitStream::ResetWritePointer()
RakNet::BitStream::Write0()
RakNet::BitStream::Write1()
RakNet::BitStream::ReadBit()
RakNet::BitStream::WriteAlignedBytes(unsigned char const*, unsigned int)
RakNet::BitStream::EndianSwapBytes(int, int)
RakNet::BitStream::ReverseBytesInPlace(unsigned char*, unsigned int)
RakNet::BitStream::WriteAlignedBytesSafe(char const*, unsigned int, unsigned int)
RakNet::BitStream::ReadAlignedBytes(unsigned char*, unsigned int)
RakNet::BitStream::ReadAlignedBytesSafe(char*, int&, int)
RakNet::BitStream::ReadAlignedBytesSafe(char*, unsigned int&, unsigned int)
RakNet::BitStream::ReadAlignedBytesSafeAlloc(char**, int&, unsigned int)
RakNet::BitStream::ReadAlignedBytesSafeAlloc(char**, unsigned int&, unsigned int)
RakNet::BitStream::SetData(unsigned char*)
RakNet::BitStream::WriteCompressed(unsigned char const*, unsigned int, bool)
RakNet::BitStream::ReadCompressed(unsigned char*, unsigned int, bool)
RakNet::BitStream::GetNumberOfBitsAllocated() const
RakNet::BitStream::PadWithZeroToByteLength(unsigned int)
RakNet::BitStream::NumberOfLeadingZeroes(signed char)
RakNet::BitStream::NumberOfLeadingZeroes(unsigned char)
RakNet::BitStream::NumberOfLeadingZeroes(short)
RakNet::BitStream::NumberOfLeadingZeroes(unsigned short)
RakNet::BitStream::NumberOfLeadingZeroes(int)
RakNet::BitStream::NumberOfLeadingZeroes(unsigned int)
RakNet::BitStream::NumberOfLeadingZeroes(long)
RakNet::BitStream::NumberOfLeadingZeroes(unsigned long)
RakNet::BitStream::AssertStreamEmpty()
RakNet::BitStream::PrintBits(char*) const
RakNet::BitStream::PrintBits() const
RakNet::BitStream::PrintHex(char*) const
RakNet::BitStream::PrintHex() const
RakNet::BitStream::CopyData(unsigned char**) const
RakNet::BitStream::IgnoreBits(unsigned int)
RakNet::BitStream::IgnoreBytes(unsigned int)
RakNet::BitStream::SetWriteOffset(unsigned int)
RakNet::BitStream::AssertCopyData()
RakNet::BitStream::IsNetworkOrderInternal()
RakNet::BitStream::ReverseBytes(unsigned char*, unsigned char*, unsigned int)
RakNet::BitStream::Read(char*)
RakNet::BitStream::Read(unsigned char*)
RakNet::BitStream::WriteAlignedVar8(char const*)
RakNet::BitStream::ReadAlignedVar8(char*)
RakNet::BitStream::WriteAlignedVar16(char const*)
RakNet::BitStream::ReadAlignedVar16(char*)
RakNet::BitStream::WriteAlignedVar32(char const*)
RakNet::BitStream::ReadAlignedVar32(char*)
RakNet::BitStream::ReadFloat16(float&, float, float)
RakNet::BitStream::SerializeFloat16(bool, float&, float, float)
RakNet::BitStream::WriteFloat16(float, float, float)
