DefaultOutOfMemoryHandler(char const*, long)
RakNet::_RakMalloc(unsigned long)
RakNet::_RakRealloc(void*, unsigned long)
RakNet::_RakFree(void*)
RakNet::_RakMalloc_Ex(unsigned long, char const*, unsigned int)
RakNet::_RakRealloc_Ex(void*, unsigned long, char const*, unsigned int)
RakNet::_RakFree_Ex(void*, char const*, unsigned int)
RakNet::_DLMallocMMap(unsigned long)
RakNet::_DLMallocDirectMMap(unsigned long)
RakNet::_DLMallocMUnmap(void*, unsigned long)
SetMalloc(void* (*)(unsigned long))
SetRealloc(void* (*)(void*, unsigned long))
SetFree(void (*)(void*))
SetMalloc_Ex(void* (*)(unsigned long, char const*, unsigned int))
SetRealloc_Ex(void* (*)(void*, unsigned long, char const*, unsigned int))
SetFree_Ex(void (*)(void*, char const*, unsigned int))
SetNotifyOutOfMemory(void (*)(char const*, long))
SetDLMallocMMap(void* (*)(unsigned long))
SetDLMallocDirectMMap(void* (*)(unsigned long))
SetDLMallocMUnmap(int (*)(void*, unsigned long))
GetMalloc()
GetRealloc()
GetFree()
GetMalloc_Ex()
GetRealloc_Ex()
GetFree_Ex()
GetDLMallocMMap()
GetDLMallocDirectMMap()
GetDLMallocMUnmap()
_DLMalloc(unsigned long)
_DLRealloc(void*, unsigned long)
_DLFree(void*)
_DLMalloc_Ex(unsigned long, char const*, unsigned int)
_DLRealloc_Ex(void*, unsigned long, char const*, unsigned int)
_DLFree_Ex(void*, char const*, unsigned int)
UseRaknetFixedHeap(unsigned long, void* (*)(unsigned long), void* (*)(unsigned long), int (*)(void*, unsigned long))
FreeRakNetFixedHeap()
