RakNet::RNS2_Berkley::SetSocketOptions()
RakNet::RNS2_Berkley::SetNonBlockingSocket(unsigned long)
RakNet::RNS2_Berkley::SetBroadcastSocket(int)
RakNet::RNS2_Berkley::GetSystemAddressIPV4And6(int, RakNet::SystemAddress*)
RakNet::RNS2_Berkley::SetMulticastInterface(int)
RakNet::RNS2_Berkley::SetIPHdrIncl(int)
RakNet::RNS2_Berkley::SetDoNotFragment(int)
RakNet::RNS2_Berkley::GetSystemAddressIPV4(int, RakNet::SystemAddress*)
RakNet::RNS2_Berkley::BindSharedIPV4(RakNet::RNS2_BerkleyBindParameters*, char const*, unsigned int)
RakNet::RNS2_Berkley::BindSharedIPV4And6(RakNet::RNS2_BerkleyBindParameters*, char const*, unsigned int)
RakNet::RNS2_Berkley::RecvFromBlockingIPV4And6(RakNet::RNS2RecvStruct*)
RakNet::RNS2_Berkley::RecvFromBlockingIPV4(RakNet::RNS2RecvStruct*)
RakNet::RNS2_Berkley::RecvFromBlocking(RakNet::RNS2RecvStruct*)
