PrepareAddrInfoHints(addrinfo*)
RakNet::SocketLayer::SetSocketOptions(int, bool, bool)
RakNet::SocketLayer::GetSubNetForSocketAndIp(RakNet::RakString)
RakNet::SocketLayer::GetMyAdapters(RakNet::NetworkAdapter*)
GetMyIP_Win32(RakNet::SystemAddress*)
RakNet::SocketLayer::GetMyIP(RakNet::SystemAddress*)
RakNet::SocketLayer::GetLocalPort(int)
RakNet::SocketLayer::GetSystemAddress(int, RakNet::SystemAddress*)
RakNet::SocketLayer::GetSystemAddress_Old(int, RakNet::SystemAddress*)
RakNet::SocketLayer::GetFirstBindableIP(char*, int)
