RakNet::StrAndBoolComp(char* const&, StrAndBool const&)
RakNet::StringTable::StringTable()
RakNet::StringTable::~StringTable()
RakNet::StringTable::AddReference()
RakNet::StringTable::RemoveReference()
RakNet::StringTable::Instance()
RakNet::StringTable::AddString(char const*, bool)
RakNet::StringTable::EncodeString(char const*, int, RakNet::BitStream*)
RakNet::StringTable::LogStringNotFound(char const*)
RakNet::StringTable::DecodeString(char*, int, RakNet::BitStream*)
