RakNet::StringCompressor::AddReference()
RakNet::StringCompressor::RemoveReference()
RakNet::StringCompressor::Instance()
RakNet::StringCompressor::StringCompressor()
RakNet::StringCompressor::GenerateTreeFromStrings(unsigned char*, unsigned int, unsigned char)
RakNet::StringCompressor::~StringCompressor()
RakNet::StringCompressor::EncodeString(char const*, int, RakNet::BitStream*, unsigned char)
RakNet::StringCompressor::DecodeString(char*, int, RakNet::BitStream*, unsigned char)
RakNet::StringCompressor::EncodeString(RakNet::RakString const*, int, RakNet::BitStream*, unsigned char)
RakNet::StringCompressor::DecodeString(RakNet::RakString*, int, RakNet::BitStream*, unsigned char)
