MineshaftPiece::createRandomShaftPiece(MineshaftData&, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&, int, int, int, int, int)
MineshaftCrossing::findCrossing(std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&, int, int, int, int)
MineshaftStairs::findStairs(std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&, int, int, int, int)
MineshaftCorridor::findCorridorSize(std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&, int, int, int, int)
MineshaftPiece::generateAndAddPiece(StructurePiece*, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&, int, int, int, int, int)
MineshaftRoom::MineshaftRoom(MineshaftData&)
MineshaftRoom::MineshaftRoom(MineshaftData&, int, Random&, int, int)
MineshaftRoom::addChildren(StructurePiece*, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&)
MineshaftRoom::postProcess(BlockSource*, Random&, BoundingBox const&)
MineshaftRoom::moveBoundingBox(int, int, int)
MineshaftCorridor::MineshaftCorridor(MineshaftData&)
MineshaftCorridor::MineshaftCorridor(MineshaftData&, int, Random&, BoundingBox const&, int)
MineshaftCorridor::addChildren(StructurePiece*, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&)
MineshaftPiece::_isSupportingBox(int, int, BlockSource*, int, int)
MineshaftCorridor::_placeCobWeb(BlockSource*, BoundingBox const&, Random&, float, int, int, int)
MineshaftCorridor::_placeSupport(BlockSource*, BoundingBox const&, int, int, int, int, int, Random&)
MineshaftCorridor::postProcessMobsAt(BlockSource*, Random&, BoundingBox const&)
MineshaftCorridor::postProcess(BlockSource*, Random&, BoundingBox const&)
MineshaftCrossing::MineshaftCrossing(MineshaftData&)
MineshaftCrossing::MineshaftCrossing(MineshaftData&, int, BoundingBox const&, int)
MineshaftCrossing::addChildren(StructurePiece*, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&)
MineshaftCrossing::_placeSupportPillar(BlockSource*, BoundingBox const&, int, int, int, int)
MineshaftCrossing::postProcess(BlockSource*, Random&, BoundingBox const&)
MineshaftStairs::MineshaftStairs(MineshaftData&)
MineshaftStairs::MineshaftStairs(MineshaftData&, int, BoundingBox const&, int)
MineshaftStairs::addChildren(StructurePiece*, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&)
MineshaftStairs::postProcess(BlockSource*, Random&, BoundingBox const&)
