MineshaftFeature::isFeatureChunk(BiomeSource const&, Random&, ChunkPos const&, unsigned int)
MineshaftFeature::createStructureStart(Dimension&, BiomeSource&, Random&, ChunkPos const&)
_isSurfaceMineshaft(BiomeSource&, ChunkPos const&)
MineshaftStart::MineshaftStart(BiomeSource&, Random&, ChunkPos const&, short)
MineshaftStart::_moveToSurface(short)
MineshaftData::MineshaftData(bool)
