OceanMonumentFeature::OceanMonumentFeature(unsigned int)
OceanMonumentFeature::getNearestGeneratedFeature(Dimension&, BiomeSource&, BlockPos const&, BlockPos&)
OceanMonumentFeature::initMobSpawnTypes(HardcodedSpawnAreaRegistry&)
OceanMonumentFeature::isFeatureChunk(BiomeSource const&, Random&, ChunkPos const&, unsigned int)
OceanMonumentFeature::createStructureStart(Dimension&, BiomeSource&, Random&, ChunkPos const&)
OceanMonumentStart::OceanMonumentStart()
OceanMonumentStart::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentStart::createMonument(Dimension&, Random&, int, int)
OceanMonumentStart::OceanMonumentStart(Dimension&, Random&, int, int)
