RoomDefinition::RoomDefinition()
RoomDefinition::RoomDefinition(int)
RoomDefinition::setConnection(unsigned char const&, std::shared_ptr<RoomDefinition>)
RoomDefinition::updateOpenings()
RoomDefinition::findSource(int)
RoomDefinition::isSpecial()
RoomDefinition::countOpenings()
OceanMonumentPiece::OceanMonumentPiece()
OceanMonumentPiece::OceanMonumentPiece(int)
OceanMonumentPiece::OceanMonumentPiece(int&, BoundingBox&)
OceanMonumentPiece::OceanMonumentPiece(int, int&, std::shared_ptr<RoomDefinition>&, int, int, int)
OceanMonumentPiece::getWorldX(int, int)
OceanMonumentPiece::addHardcodedSpawnAreas(LevelChunk&) const
OceanMonumentPiece::getWorldZ(int, int)
OceanMonumentPiece::generateWaterBox(BlockSource*, BoundingBox const&, int, int, int, int, int, int, bool)
OceanMonumentPiece::generateDefaultFloor(BlockSource*, BoundingBox const&, int, int, bool)
OceanMonumentPiece::generateBoxOnFillOnly(BlockSource*, BoundingBox const&, int, int, int, int, int, int, Block const&)
OceanMonumentPiece::spawnElder(BlockSource*, BoundingBox const&, int, int, int)
OceanMonumentPiece::chunkIntersects(BoundingBox const&, int, int, int, int)
OceanMonumentPiece::postProcessMobsAt(BlockSource*, Random&, BoundingBox const&)
MonumentBuilding::MonumentBuilding(Random&, int, int, int&)
MonumentBuilding::generateRoomGraph(Random&)
MonumentBuilding::MonumentBuilding()
MonumentBuilding::postProcess(BlockSource*, Random&, BoundingBox const&)
MonumentBuilding::generateWing(bool, int, BlockSource*, Random&, BoundingBox const&)
MonumentBuilding::generateEntranceArchs(BlockSource*, Random&, BoundingBox const&)
MonumentBuilding::generateEntranceWall(BlockSource*, Random&, BoundingBox const&)
MonumentBuilding::generateRoofPiece(BlockSource*, Random&, BoundingBox const&)
MonumentBuilding::generateLowerWall(BlockSource*, Random&, BoundingBox const&)
MonumentBuilding::generateMiddleWall(BlockSource*, Random&, BoundingBox const&)
MonumentBuilding::generateUpperWall(BlockSource*, Random&, BoundingBox const&)
MonumentBuilding::postProcessMobsAt(BlockSource*, Random&, BoundingBox const&)
OceanMonumentEntryRoom::OceanMonumentEntryRoom()
OceanMonumentEntryRoom::OceanMonumentEntryRoom(int&, std::shared_ptr<RoomDefinition>&)
OceanMonumentEntryRoom::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentSimpleRoom::OceanMonumentSimpleRoom()
OceanMonumentSimpleRoom::OceanMonumentSimpleRoom(int&, std::shared_ptr<RoomDefinition>&, Random&)
OceanMonumentSimpleRoom::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentSimpleTopRoom::OceanMonumentSimpleTopRoom()
OceanMonumentSimpleTopRoom::OceanMonumentSimpleTopRoom(int&, std::shared_ptr<RoomDefinition>&)
OceanMonumentSimpleTopRoom::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentDoubleYRoom::OceanMonumentDoubleYRoom()
OceanMonumentDoubleYRoom::OceanMonumentDoubleYRoom(int&, std::shared_ptr<RoomDefinition>&)
OceanMonumentDoubleYRoom::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentDoubleXRoom::OceanMonumentDoubleXRoom()
OceanMonumentDoubleXRoom::OceanMonumentDoubleXRoom(int&, std::shared_ptr<RoomDefinition>&)
OceanMonumentDoubleXRoom::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentDoubleZRoom::OceanMonumentDoubleZRoom()
OceanMonumentDoubleZRoom::OceanMonumentDoubleZRoom(int&, std::shared_ptr<RoomDefinition>&)
OceanMonumentDoubleZRoom::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentDoubleXYRoom::OceanMonumentDoubleXYRoom()
OceanMonumentDoubleXYRoom::OceanMonumentDoubleXYRoom(int&, std::shared_ptr<RoomDefinition>&)
OceanMonumentDoubleXYRoom::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentDoubleYZRoom::OceanMonumentDoubleYZRoom()
OceanMonumentDoubleYZRoom::OceanMonumentDoubleYZRoom(int&, std::shared_ptr<RoomDefinition>&)
OceanMonumentDoubleYZRoom::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentCoreRoom::OceanMonumentCoreRoom()
OceanMonumentCoreRoom::OceanMonumentCoreRoom(int&, std::shared_ptr<RoomDefinition>&)
OceanMonumentCoreRoom::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentWingRoom::OceanMonumentWingRoom()
OceanMonumentWingRoom::OceanMonumentWingRoom(int&, BoundingBox&, int, bool)
OceanMonumentWingRoom::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentWingRoom::postProcessMobsAt(BlockSource*, Random&, BoundingBox const&)
OceanMonumentPenthouse::OceanMonumentPenthouse()
OceanMonumentPenthouse::OceanMonumentPenthouse(int&, BoundingBox&)
OceanMonumentPenthouse::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanMonumentPenthouse::postProcessMobsAt(BlockSource*, Random&, BoundingBox const&)
FitSimpleRoom::fits(std::shared_ptr<RoomDefinition>&)
FitSimpleRoom::create(int&, std::shared_ptr<RoomDefinition>&, Random&)
FitSimpleTopRoom::fits(std::shared_ptr<RoomDefinition>&)
FitSimpleTopRoom::create(int&, std::shared_ptr<RoomDefinition>&, Random&)
FitDoubleYRoom::fits(std::shared_ptr<RoomDefinition>&)
FitDoubleYRoom::create(int&, std::shared_ptr<RoomDefinition>&, Random&)
FitDoubleXRoom::fits(std::shared_ptr<RoomDefinition>&)
FitDoubleXRoom::create(int&, std::shared_ptr<RoomDefinition>&, Random&)
FitDoubleZRoom::fits(std::shared_ptr<RoomDefinition>&)
FitDoubleZRoom::create(int&, std::shared_ptr<RoomDefinition>&, Random&)
FitDoubleXYRoom::fits(std::shared_ptr<RoomDefinition>&)
FitDoubleXYRoom::create(int&, std::shared_ptr<RoomDefinition>&, Random&)
FitDoubleYZRoom::fits(std::shared_ptr<RoomDefinition>&)
FitDoubleYZRoom::create(int&, std::shared_ptr<RoomDefinition>&, Random&)
