ScatteredFeaturePiece::ScatteredFeaturePiece(int, int, int, int, int, int)
ScatteredFeaturePiece::updateAverageGroundHeight(BlockSource*, BoundingBox const&, int)
DesertPyramidPiece::DesertPyramidPiece(int, int)
DesertPyramidPiece::postProcess(BlockSource*, Random&, BoundingBox const&)
JunglePyramidPiece::JunglePyramidPiece(int, int)
JunglePyramidPiece::postProcess(BlockSource*, Random&, BoundingBox const&)
SwamplandHut::SwamplandHut(int, int)
SwamplandHut::addHardcodedSpawnAreas(LevelChunk&) const
SwamplandHut::placeCauldron(BlockSource*, Random&, int, int, int, BoundingBox const&)
SwamplandHut::postProcess(BlockSource*, Random&, BoundingBox const&)
SwamplandHut::postProcessMobsAt(BlockSource*, Random&, BoundingBox const&)
Igloo::Igloo(int, int)
Igloo::postProcessMobsAt(BlockSource*, Random&, BoundingBox const&)
Igloo::postProcess(BlockSource*, Random&, BoundingBox const&)
