StructureTelemetryClientData::StructureTelemetryClientData()
StructureTelemetryClientData::resetCounts()
StructureTelemetryClientData::increaseSizeEditCount()
StructureTelemetryClientData::increaseOffsetEditCount()
StructureTelemetryClientData::increaseRotationEditCount()
StructureTelemetryClientData::increaseMirrorEditCount()
StructureTelemetryClientData::getSizeEditCount() const
StructureTelemetryClientData::getOffsetEditCount() const
StructureTelemetryClientData::getRotationEditCount() const
StructureTelemetryClientData::getMirrorEditCount() const
StructureTelemetryClientData::hasAnyFieldBeenEdited() const
StructureTelemetryServerData::StructureTelemetryServerData()
StructureTelemetryServerData::setHasBeenActivedByRedstone()
StructureTelemetryServerData::hasBeenActivatedByRedstone()
StructureTelemetryServerData::setHasLoadedIntoUnloadedChunks(BlockPos const&)
StructureTelemetryServerData::hasBeenLoadedIntoUnloadedChunks(BlockPos const&)
