StructureManager::StructureManager()
StructureManager::~StructureManager()
StructureManager::getOrCreateLegacy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
StructureManager::_getLegacy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
StructureManager::_createAndLoadStructure(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
StructureManager::load(StructureTemplate&)
StructureManager::_readLegacyStructure(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
StructureManager::loadLegacy(LegacyStructureTemplate&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
StructureManager::getOrCreate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
StructureManager::getStructure(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
StructureManager::saveToLevel(StructureTemplate const&)
StructureManager::exportStructure(StructureTemplate const&, Core::Path const&)
StructureManager::setLevelStorage(LevelStorage*)
StructureManager::setPackManager(ResourcePackManager&)
StructureManager::createStructureDataExportPacket(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, StructureTemplateResponseType)
StructureManager::clearLoadedStructures()
