StructureFeature::addFeature(Dimension&, Random&, ChunkPos const&, BiomeSource&)
StructureFeature::StructureFeature(unsigned int)
StructureFeature::~StructureFeature()
StructureFeature::~StructureFeature()
StructureFeature::initMobSpawnTypes(HardcodedSpawnAreaRegistry&)
StructureFeature::createBlueprints(Dimension&, ChunkPos const&, BiomeSource&)
StructureFeature::foreachIntersectingStructureStart(BoundingBox const&, std::function<void (StructureStart&)>)
StructureFeature::postProcess(BlockSource*, Random&, int, int)
StructureFeature::generateHardcodedMobSpawns(LevelChunk&)
StructureFeature::postProcessMobsAt(BlockSource*, int, int, Random&)
StructureFeature::debugRender()
StructureFeature::isInsideFeature(int, int, int)
StructureFeature::getStructureAt(int, int, int)
StructureFeature::getGuesstimatedFeaturePositions()
StructureFeature::setRandomSeedFor(Random&, int, int, int, unsigned int)
StructureFeature::isInsideBoundingFeature(int, int, int)
StructureFeature::getNearestGeneratedFeature(Dimension&, BiomeSource&, BlockPos const&, BlockPos&)
StructureFeature::findNearestFeaturePositionBySpacing(Dimension&, StructureFeature&, BiomeSource&, BlockPos const&, BlockPos&, int, int, int, bool, int, bool)
chunkPosAABBsIntersect(ChunkPos const&, ChunkPos const&, ChunkPos const&, ChunkPos const&)
chunkPosAABBContains(ChunkPos const&, ChunkPos const&, ChunkPos)
StructureFeature::findFarAwayStructures(buffer_span<ChunkPos>, unsigned int)
StructureFeature::garbageCollectBlueprints(buffer_span<ChunkPos>, unsigned int)
