convertTorchDirection(Facing::Name)
_facingToDirection(unsigned char)
_facingToVineDirection(unsigned char)
_facingToLogDirection(unsigned char)
_facingToStrippedLogDirection(unsigned char)
_isRotatingWoodBlock(Block const&)
LegacyStructureTemplate::_mapToData(Block const&, LegacyStructureSettings const&)
LegacyStructureTemplate::_mapPropertyToExtraBlock(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
LegacyStructureTemplate::_mapToProperty(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Block const&)
LegacyStructureTemplate::_mapToBlock(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
LegacyStructureTemplate::_mapTag(std::unique_ptr<CompoundTag, std::default_delete<CompoundTag> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
