StructureHelpers::getFacingDirectionRotation(int, unsigned short)
StructureHelpers::getDirectionRotation(int, unsigned short)
StructureHelpers::getWeirdoDirectionRotation(int, unsigned short)
StructureHelpers::getDoorRotation(int, unsigned short)
StructureHelpers::getRailRotation(int, unsigned short)
StructureHelpers::getTorchRotation(int, unsigned short)
StructureHelpers::createChest(StructurePiece&, BlockSource&, BoundingBox const&, Random&, int, int, int, unsigned char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
StructureHelpers::createMinecartChest(StructurePiece&, BlockSource&, BoundingBox const&, Random&, int, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
StructureHelpers::createDispenser(StructurePiece&, BlockSource&, BoundingBox const&, Random&, int, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
StructureHelpers::createDoor(StructurePiece&, BlockSource&, BoundingBox const&, Random&, int, int, int, int)
StructureHelpers::fillColumnDown(StructurePiece&, BlockSource&, Block const&, int, int, int, BoundingBox const&)
