MoveToVillageGoal::MoveToVillageGoal(Mob&, float, float, float, int)
MoveToVillageGoal::start()
MoveToVillageGoal::canUse()
MoveToVillageGoal::_tryGetCurrentVillage()
MoveToVillageGoal::tick()
MoveToVillageGoal::_moveToBlock()
MoveToVillageGoal::_selectRandomPosInVillage()
MoveToVillageGoal::canContinueToUse()
MoveToVillageGoal::isValidTarget(BlockSource&, BlockPos const&)
MoveToVillageGoal::appendDebugInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const
