PetSleepWithOwnerGoal::PetSleepWithOwnerGoal(Mob&, float, int, int, float)
PetSleepWithOwnerGoal::canUse()
PetSleepWithOwnerGoal::canContinueToUse()
PetSleepWithOwnerGoal::start()
PetSleepWithOwnerGoal::stop()
PetSleepWithOwnerGoal::tick()
PetSleepWithOwnerGoal::findTargetBlock()
PetSleepWithOwnerGoal::isValidTarget(BlockSource&, BlockPos const&)
PetSleepWithOwnerGoal::appendDebugInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const
PetSleepWithOwnerGoal::_nextStartTick()
PetSleepWithOwnerGoal::_moveToBlock()
