StompBlockGoal::StompBlockGoal(Block const*, Mob&, double, int, int, int, float, int)
StompBlockGoal::canUse()
StompBlockGoal::canContinueToUse()
StompBlockGoal::start()
StompBlockGoal::stop()
StompBlockGoal::tick()
StompBlockGoal::_getPosWithBlock(BlockPos) const
StompBlockGoal::appendDebugInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const
StompBlockGoal::isValidTarget(BlockSource&, BlockPos const&)
StompBlockGoal::_moveToBlock()
StompBlockGoal::_createBreakProgressParticles(Level&, BlockSource&, BlockPos)
StompBlockGoal::_createDestroyParticles(Level&, BlockSource&, BlockPos)
StompBlockGoal::_playBreakProgressSound(Level&, BlockSource&, BlockPos)
StompBlockGoal::_playDestroySound(Level&, BlockSource&, BlockPos)
StompBlockGoal::_canReach(BlockPos const&)
