WorkGoal::WorkGoal(Mob&, float, int, int, int, int, bool, int, DefinitionTrigger const&)
WorkGoal::canUse()
WorkGoal::_updateCooldown()
WorkGoal::_isInsideOrIsNotRaining()
WorkGoal::canContinueToUse()
WorkGoal::_shouldTestForRainFallingOnPOI()
WorkGoal::start()
WorkGoal::stop()
WorkGoal::tick()
WorkGoal::_tryResupplyTrades()
WorkGoal::appendDebugInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const
