ChemistryIngredient::ChemistryIngredient(ElementType, int)
ChemistryIngredient::ChemistryIngredient(CompoundType, int)
ChemistryIngredient::ChemistryIngredient(ItemInstance const&)
CraftableCompounds::getCompound(std::vector<ItemStack, std::allocator<ItemStack> > const&)
CraftableCompounds::_getCompoundId[abi:cxx11](std::vector<ItemStack, std::allocator<ItemStack> > const&)
CraftableCompounds::getComponents(ItemDescriptor const&)
CraftableCompounds::getReaction(std::vector<ItemStack, std::allocator<ItemStack> > const&)
CraftableCompounds::getContainerType(std::vector<ItemStack, std::allocator<ItemStack> > const&)
CraftableCompounds::CraftableCompounds()
CraftableCompounds::~CraftableCompounds()
CraftableCompounds::~CraftableCompounds()
CraftableCompounds::registerCompounds()
CraftableCompounds::_registerCompound(std::vector<ChemistryIngredient, std::allocator<ChemistryIngredient> > const&, CompoundType, LabTableReactionType, CompoundContainerType, int)
CraftableCompounds::_registerCompound(std::vector<ChemistryIngredient, std::allocator<ChemistryIngredient> > const&, ItemStack const&, LabTableReactionType, CompoundContainerType)
CraftableCompounds::_registerCompound(std::vector<ItemStack, std::allocator<ItemStack> > const&, ItemStack const&, LabTableReactionType, CompoundContainerType)
