TickingArea::TickingArea(Dimension&, mce::UUID, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Bounds const&, bool)
TickingArea::TickingArea(Dimension&, mce::UUID, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ActorUniqueID, Bounds const&, bool, float, bool)
TickingArea::TickingArea(Dimension&, mce::UUID, Bounds const&, ActorUniqueID)
TickingArea::TickingArea(Dimension&, mce::UUID, Bounds const&, ActorUniqueID, float)
TickingArea::~TickingArea()
TickingArea::~TickingArea()
TickingArea::getDescription() const
TickingArea::tick(Tick const&, bool)
TickingArea::tickSeasons(Random&)
TickingArea::updatePosition(Vec3 const&)
TickingArea::center()
TickingArea::_save()
TickingArea::findOwner(unsigned char&)
TickingArea::setRegionForEntity(Actor&)
TickingArea::remove()
TickingArea::onComponentChanged(unsigned int, float, bool)
TickingArea::onChunkLoaded(LevelChunk&)
TickingArea::onChunkDiscarded(LevelChunk&)
