DBChunkStorageKey::DBChunkStorageKey(LevelChunk const&)
DBChunkStorageKey::DBChunkStorageKey(ChunkPos const&, AutomaticID<Dimension, int>)
DBChunkStorageKey::asSpan() const
DBChunkStorageKey::hashCode() const
DBChunkStorage::DBChunkStorage(std::unique_ptr<ChunkSource, std::default_delete<ChunkSource> >, DBStorage&, Scheduler&)
DBChunkStorage::~DBChunkStorage()
DBChunkStorage::~DBChunkStorage()
DBChunkStorage::shutdown()
DBChunkStorage::isShutdownDone()
DBChunkStorage::flushPendingWrites()
DBChunkStorage::_writeBatch()
join[abi:cxx11](gsl::basic_string_span<char const, -1l>, LevelChunk::Tag)
join[abi:cxx11](gsl::basic_string_span<char const, -1l>, LevelChunk::Tag, unsigned int)
DBChunkStorage::_hasChunkUncached(DBChunkStorageKey const&)
DBChunkStorage::_hasChunk(DBChunkStorageKey const&)
DBChunkStorage::loadChunk(LevelChunk&, bool)
DBChunkStorage::_loadChunkFromDB(LevelChunk&)
DBChunkStorage::postProcess(ChunkViewSource&)
DBChunkStorage::_applyChunkFixup(LevelChunk*, BlockSource&)
DBChunkStorage::_upgradeFix(LevelChunk&, BlockSource&)
DBChunkStorage::checkAndReplaceChunk(ChunkViewSource&, LevelChunk&)
DBChunkStorage::_loadAndBlendFromDB(LevelChunk&)
DBChunkStorage::hintDiscardBatchBegin()
DBChunkStorage::_serializeChunk(LevelChunk const&, DBStorageWriteBatch&)
DBChunkStorage::acquireDiscarded(std::unique_ptr<LevelChunk, LevelChunkFinalDeleter>)
DBChunkStorage::hintDiscardBatchEnd()
DBChunkStorage::_getBuffer()
DBChunkStorage::saveLiveChunk(LevelChunk&)
DBChunkStorage::freeCaches()
DBChunkStorage::registerUpgradeFixHandler(std::function<void (LevelChunk&, BlockSource&)>)
