EncryptedProxyEnv::EncryptedProxyEnv(leveldb::Env*, ContentIdentity const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
EncryptedProxyEnv::NewSequentialFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::SequentialFile**)
EncryptedProxyEnv::NewRandomAccessFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::RandomAccessFile**)
EncryptedProxyEnv::NewWritableFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::WritableFile**)
EncryptedProxyEnv::DeleteFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
EncryptedProxyEnv::RenameFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
