FlushableStorageAreaEnv::FlushableStorageAreaEnv(leveldb::Env*, std::shared_ptr<Core::FileStorageArea>)
FlushableStorageAreaEnv::~FlushableStorageAreaEnv()
FlushableStorageAreaEnv::_flushStorageArea()
FlushableStorageAreaEnv::~FlushableStorageAreaEnv()
FlushableStorageAreaEnv::flushToPermanentStorage()
