InMemoryEnv::InMemoryEnv(leveldb::Env*, Core::Path const&)
InMemoryEnv::~InMemoryEnv()
InMemoryEnv::_flushWithTransaction()
InMemoryEnv::~InMemoryEnv()
InMemoryEnv::NewSequentialFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::SequentialFile**)
InMemoryEnv::NewRandomAccessFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::RandomAccessFile**)
InMemoryEnv::NewWritableFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::WritableFile**)
InMemoryEnv::NewAppendableFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::WritableFile**)
InMemoryEnv::DeleteFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
InMemoryEnv::RenameFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
InMemoryEnv::FileExists(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
InMemoryEnv::GetChildren(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)
InMemoryEnv::flushToPermanentStorage()
