LegacyChunkStorage::LegacyChunkStorage(std::unique_ptr<ChunkSource, std::default_delete<ChunkSource> >, LevelStorage&, StorageVersion, Biome&)
LegacyChunkStorage::_loadEntities()
LegacyChunkStorage::~LegacyChunkStorage()
LegacyChunkStorage::~LegacyChunkStorage()
LegacyChunkStorage::_collectInfo(bool*)
LegacyChunkStorage::_isImported(ChunkPos const&)
LegacyChunkStorage::_markChunkAsImported(ChunkPos const&)
LegacyChunkStorage::_openRegionFile()
LegacyChunkStorage::_loadChunk(LevelChunk&)
LegacyChunkStorage::loadChunk(LevelChunk&, bool)
LegacyChunkStorage::saveLiveChunk(LevelChunk&)
LegacyChunkStorage::acquireDiscarded(std::unique_ptr<LevelChunk, LevelChunkFinalDeleter>)
