PhotoStorage::PhotoStorage(Core::Path const&)
PhotoStorage::_readManifest()
PhotoStorage::getPhotoPath[abi:cxx11](Player&)
PhotoStorage::getPhotoPath[abi:cxx11]()
PhotoStorage::getBookPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PhotoStorage::getBookPath[abi:cxx11]()
PhotoStorage::storeLoosePhoto(Player&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PhotoStorage::_writeFile(Core::Path, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PhotoStorage::storeBookPhoto(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PhotoStorage::getLoosePhoto(Player&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
PhotoStorage::_readFile(Core::Path, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
PhotoStorage::getBookPhoto(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
PhotoStorage::deleteLoosePhoto(Player&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PhotoStorage::deleteBookPhoto(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PhotoStorage::isValidLoosePhoto(Player&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PhotoStorage::_isValidFile(Core::Path)
PhotoStorage::isValidBookPhoto(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PhotoStorage::setValidLoosePhoto(Player&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PhotoStorage::_addValidFile(Core::Path)
PhotoStorage::getLoosePhotos(Player&, std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&)
PhotoStorage::_writeManifest()
