PlayerDataSystem::forEachIdByPrecedence(PlayerStorageIds const&, std::function<bool (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)
PlayerDataSystem::getPlayerFilename(Core::Path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PlayerDataSystem::serverKey[abi:cxx11](LevelStorage&, gsl::basic_string_span<char const, -1l>)
PlayerDataSystem::playerKey[abi:cxx11](gsl::basic_string_span<char const, -1l>)
PlayerDataSystem::serverKey[abi:cxx11](LevelStorage&, Player const&)
PlayerDataSystem::legacyConsolePlayerKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PlayerDataSystem::loadPlayerDataFromTag(LevelStorage&, gsl::basic_string_span<char const, -1l>)
PlayerDataSystem::getServerId[abi:cxx11](LevelStorage&, PlayerStorageIds const&)
PlayerDataSystem::loadPlayerData(LevelStorage&, PlayerStorageIds const&, bool)
PlayerDataSystem::loadLocalPlayerData(LevelStorage&)
PlayerDataSystem::legacyLoadPlayer(LevelStorage&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PlayerDataSystem::legacyLoadClientPlayer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Core::Path const&)
PlayerDataSystem::loadLostData(LevelStorage&, PlayerStorageIds const&, bool)
