SavedDataStorage::SavedDataStorage(LevelStorage*)
SavedDataStorage::loadAndSet(SavedData&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
SavedDataStorage::set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, SavedData&)
SavedDataStorage::save()
SavedDataStorage::_save(SavedData const&)
