ActorClassTree::getEntityTypeIdLegacy(ActorType)
ActorClassTree::isMobLegacy(ActorType)
ActorClassTree::isMob(ActorType)
ActorClassTree::isTypeInstanceOf(ActorType, ActorType)
ActorClassTree::isInstanceOf(Actor const&, ActorType)
ActorClassTree::isOfType(ActorType, ActorType)
ActorClassTree::hasCategory(ActorCategory const&, ActorCategory)
ActorClassTree::isHangingEntity(Actor const&)
