ActorDefinitionGroup::ActorDefinitionGroup(Level&, ResourcePackManager&, IMinecraftEventing&, bool)
ActorDefinitionGroup::_getResources(Level&)
ActorDefinitionGroup::~ActorDefinitionGroup()
ActorDefinitionGroup::~ActorDefinitionGroup()
ActorDefinitionGroup::_loadTemplates(Level&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Json::Value, SemVersion const&)
ActorDefinitionGroup::_loadEvents(Json::Value, ActorDefinition&)
ActorDefinitionGroup::tryReadEntityResourceFile(PackInstance&, Core::Path const&, Json::Value&)
ActorDefinitionGroup::loadActorDefinitionFormatVersion(Json::Value const&, SemVersion&)
ActorDefinitionGroup::loadActorDefinitionIdentifier(Json::Value const&, SemVersion const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
ActorDefinitionGroup::loadActorDefinitionRuntimeIdentifier(Json::Value const&, SemVersion const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
ActorDefinitionGroup::getComponentFactory()
ActorDefinitionGroup::setComponentFactory(ActorComponentFactory*)
ActorDefinitionGroup::_setupAnimationResourceDefinitionMap(ActorDefinition&, Level&)
ActorDefinitionGroup::hasComponent(Util::HashString const&, Json::Value const&, Json::Value const&) const
ActorDefinitionGroup::hasPlayerAsTarget(Json::Value const&) const
ActorDefinitionGroup::tryGetDefinition(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ActorDefinitionGroup::tryGetDefinitionGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ActorDefinitionGroup::_addRef(ActorDefinitionPtr&)
ActorDefinitionGroup::_removeRef(ActorDefinitionPtr&)
