ActorDefinitionPtr::ActorDefinitionPtr()
ActorDefinitionPtr::ActorDefinitionPtr(ActorDefinitionGroup&, ActorDefinition&)
ActorDefinitionPtr::onGroupReloaded()
ActorDefinitionPtr::ActorDefinitionPtr(ActorDefinitionPtr&&)
ActorDefinitionPtr::_move(ActorDefinitionPtr&&)
ActorDefinitionPtr::operator=(ActorDefinitionPtr&&)
ActorDefinitionPtr::ActorDefinitionPtr(ActorDefinitionPtr const&)
ActorDefinitionPtr::operator=(ActorDefinitionPtr const&)
ActorDefinitionPtr::_deref()
ActorDefinitionPtr::~ActorDefinitionPtr()
