EntityTypeToStringAndNamespace(ActorType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
EntityTypeToString[abi:cxx11](ActorType, ActorTypeNamespaceRules)
EntityTypeToLocString[abi:cxx11](ActorType, ActorTypeNamespaceRules)
EntityTypeToFormattedLocString[abi:cxx11](ActorType, ActorTypeNamespaceRules)
EntityTypeIdWithoutCategories[abi:cxx11](ActorType, ActorTypeNamespaceRules)
EntityCanonicalName(ActorType)
lookupActualEntityType(ActorType)
EntityTypeFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
EntityTypeResolveAlias(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ActorTypeNamespaceRules)
forEachEntityType(std::function<bool (ActorType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)
