_createElderGuardian(ActorDefinitionGroup*, ActorDefinitionIdentifier const&)
_entityNotCreateable(ActorDefinitionGroup*, ActorDefinitionIdentifier const&)
ActorFactory::ActorFactory(Level&)
ActorFactory::setDefinitionGroup(ActorDefinitionGroup*)
ActorFactory::clearDefinitionGroup()
ActorFactory::_constructActor(ActorDefinitionIdentifier const&, Vec3 const&, Vec2 const&)
ActorFactory::loadEntity(CompoundTag const*, DataLoadHelper&)
ActorFactory::fixLegacyEntity(BlockSource&, CompoundTag const*)
ActorFactory::createEntity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ActorDefinitionIdentifier const&, Actor*, Vec3 const&, Vec2 const&)
ActorFactory::createSpawnedEntity(ActorDefinitionIdentifier const&, Actor*, Vec3 const&, Vec2 const&)
ActorFactory::createSummonedEntity(ActorDefinitionIdentifier const&, Actor*, Vec3 const&)
ActorFactory::createBornEntity(ActorDefinitionIdentifier const&, Actor*)
ActorFactory::createTransformedEntity(ActorDefinitionIdentifier const&, Actor*)
ActorFactory::_createDummySpawnedEntity(ActorDefinitionIdentifier const&, Actor*, Vec3 const&, Vec2 const&)
ActorFactory::createBornEntity(ActorDefinitionIdentifier const&, BlockPos const&)
ActorFactory::buildSummonEntityTypeEnum[abi:cxx11](bool)
ActorFactory::lookupEntityType(ActorDefinitionIdentifier const&)
ActorFactory::generateActorIdentifierList[abi:cxx11]() const
ActorFactory::_digestIdentifierListFromServer(std::vector<ActorInfo, std::allocator<ActorInfo> > const&)
ActorFactory::setEntityInitializer(std::shared_ptr<IEntityInitializer>)
