FeedItem::setItem(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
FeedItem::addEffect(FeedItem::Effect const&)
Description::startParsing(Json::Value&, Json::Value&, char const*)
Description::deserializeData(Json::Value&)
Description::parseDescription(Json::Value&)
Description::registerAttributes()
Description::registerJsonName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Description::registerProperties()
Description::registerTriggers()
Description::registerComponents()
Description::getName[abi:cxx11](int)
Description::getId(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
