FishingHook::FishingHook(ActorDefinitionGroup*, ActorDefinitionIdentifier const&)
FishingHook::~FishingHook()
FishingHook::getOwner()
FishingHook::~FishingHook()
FishingHook::reloadHardcoded(Actor::InitializationMethod, VariantParameterList const&)
FishingHook::shoot(Vec3, float, float)
FishingHook::save(CompoundTag&)
FishingHook::lerpTo(Vec3 const&, Vec2 const&, int)
FishingHook::lerpMotion(Vec3 const&)
FishingHook::_pullCloser(Actor&, float)
FishingHook::retrieve()
FishingHook::getTargetUniqueID() const
FishingHook::_lerpServerPos()
FishingHook::_serverNibble()
FishingHook::_getServerFishSpeed()
FishingHook::_serverHooked()
FishingHook::handleEntityEvent(ActorEvent, int)
FishingHook::_fishPosEvent()
FishingHook::_fishhookEvent()
FishingHook::_fishTeaseEvent()
FishingHook::_serverTease()
FishingHook::_serverLured()
FishingHook::_updateServer()
FishingHook::_hitCheck()
FishingHook::_getWaterPercentage()
FishingHook::_updateGravity()
FishingHook::normalTick()
FishingHook::getTarget()
FishingHook::getSourceUniqueID() const
