Hopper::Hopper(int, bool)
Hopper::_addItem(Container&, ItemActor&)
Hopper::_addItem(BlockSource&, Container&, ItemStack&, int, int)
Hopper::_tryMoveInItem(BlockSource&, Container&, ItemStack&, int, int, int)
Hopper::_getItemAt(BlockSource&, Vec3 const&)
Hopper::_tryMoveItems(BlockSource&, Container&, Vec3 const&, int, bool)
Hopper::_isEmptyContainer(Container&, int)
Hopper::_pushOutItems(BlockSource&, Container&, Vec3 const&, int)
Hopper::_isFullContainer(BlockSource&, Container&, int)
Hopper::_pullInItems(BlockSource&, Container&, Vec3 const&)
Hopper::setCooldownTime(int)
Hopper::_canPlaceItemInContainer(BlockSource&, Container&, ItemStack&, int, int)
Hopper::_tryTakeInItemFromSlot(BlockSource&, Container&, Container&, int, int)
Hopper::_canTakeItemFromContainer(BlockSource&, Container&, ItemStack&, int, int)
Hopper::_getSourceContainer(BlockSource&, Vec3 const&)
Hopper::_getAttachedContainer(BlockSource&, Vec3 const&, int)
Hopper::_tryPushToComposter(BlockSource&, Container&, BlockPos, int)
Hopper::_getContainerAt(BlockSource&, Vec3 const&)
Hopper::isOnCooldown()
Hopper::getCooldownTime() const
Hopper::setMoveItemSpeed(int)
