LeashFenceKnotActor::LeashFenceKnotActor(ActorDefinitionGroup*, ActorDefinitionIdentifier const&)
LeashFenceKnotActor::reloadHardcoded(Actor::InitializationMethod, VariantParameterList const&)
LeashFenceKnotActor::setDir(int)
LeashFenceKnotActor::getWidth() const
LeashFenceKnotActor::getHeight() const
LeashFenceKnotActor::dropItem()
LeashFenceKnotActor::getShadowRadius() const
LeashFenceKnotActor::isPickable()
LeashFenceKnotActor::shouldRenderAtSqrDistance(double)
LeashFenceKnotActor::addAdditionalSaveData(CompoundTag&)
LeashFenceKnotActor::readAdditionalSaveData(CompoundTag const&, DataLoadHelper&)
LeashFenceKnotActor::remove()
LeashFenceKnotActor::removeAnimals(Player*)
LeashFenceKnotActor::numberofAnimalsAttached()
LeashFenceKnotActor::getInteraction(Player&, ActorInteraction&, Vec3 const&)
LeashFenceKnotActor::teleportTo(Vec3 const&, bool, int, int)
LeashFenceKnotActor::wouldSurvive(BlockSource&)
LeashFenceKnotActor::recalculateBoundingBox()
LeashFenceKnotActor::_onSizeUpdated()
findKnotAt(BlockSource&, BlockPos const&)
