CommandUtils::createItemInstance(Item const*, int, int)
CommandUtils::createItemInstance(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)
CommandUtils::createItemStack(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)
CommandUtils::createItemStacks(ItemInstance const&, int, int&)
CommandUtils::addItemInstanceComponents(ItemInstance&, Json::Value const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
CommandUtils::addtoCSVList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
CommandUtils::displayLocalizableMessage(bool, Player&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
CommandUtils::spawnEntityAt(BlockSource&, Vec3 const&, ActorDefinitionIdentifier const&, ActorUniqueID&, Actor*)
CommandUtils::alterSpawnableEntities(LevelData&, ActorDefinitionIdentifier const&, ActorDefinitionIdentifier&)
CommandUtils::isPlayerSpawnedMob(Actor*, Actor*)
CommandUtils::toJsonResult(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Json::Value const&)
CommandUtils::getFeetPos(Actor const*)
CommandUtils::getFeetBlockPos(Actor const*)
CommandUtils::createMapData(Actor&, ItemInstance&, CommandOutput&)
CommandUtils::clearBlockEntityContents(BlockSource&, BlockPos const&)
CommandUtils::getInvalidCommandEntities()
CommandUtils::isValidCommandEntity(std::vector<ActorType, std::allocator<ActorType> > const&, ActorType)
CommandUtils::getOriginPlayer(CommandOrigin const&)
