NetherFortressFeature::NetherFortressFeature(unsigned int&)
NetherFortressFeature::initMobSpawnTypes(HardcodedSpawnAreaRegistry&)
NetherFortressFeature::isFeatureChunk(BiomeSource const&, Random&, ChunkPos const&, unsigned int)
NetherFortressFeature::clearCachedBuildings()
NetherFortressFeature::createStructureStart(Dimension&, BiomeSource&, Random&, ChunkPos const&)
NetherFortressStart::NetherFortressStart()
NetherFortressStart::NetherFortressStart(Random&, int, int)
