OceanRuinPieces::_getSmallWarmRuin[abi:cxx11](Random&)
OceanRuinPieces::_getBigWarmRuin[abi:cxx11](Random&)
OceanRuinPieces::_addClusterRuins(StructureManager&, Random&, Rotation const&, BlockPos const&, OceanRuinConfiguration const&, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&)
OceanRuinPieces::_allPositions(Random&, int, int, int)
OceanRuinPieces::_addPiece(StructureManager&, BlockPos const&, Rotation const&, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&, OceanRuinConfiguration const&, bool, float)
OceanRuinPieces::init()
OceanRuinPieces::addPieces(StructureManager&, BlockPos const&, Rotation const&, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&, OceanRuinConfiguration const&)
OceanRuinPieces::OceanRuinPiece::OceanRuinPiece(StructureManager&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, BlockPos const&, Rotation, float, bool, OceanTempCategory)
OceanRuinPieces::OceanRuinPiece::_loadTemplate()
OceanRuinPieces::OceanRuinPiece::OceanRuinPiece(StructureManager&)
OceanRuinPieces::OceanRuinPiece::postProcess(BlockSource*, Random&, BoundingBox const&)
OceanRuinPieces::OceanRuinPiece::_getHeight(BlockPos&, BlockSource*, BlockPos const&)
OceanRuinPieces::OceanRuinPiece::_handleDataMarker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, BlockPos const&, BlockSource&, Random&, BoundingBox const&)
OceanRuinPieces::OceanRuinPiece::getChestReplacer(OceanTempCategory, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
