PillagerOutpostPieces::_getMscFeature(Random&)
PillagerOutpostPieces::_addScatteredPieces(StructureManager&, Random&, Rotation const&, BlockPos const&, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Dimension&)
PillagerOutpostPieces::_getPiecePositions(Random&)
PillagerOutpostPieces::_addPiece(StructureManager&, BlockPos const&, Rotation const&, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&, Dimension&)
PillagerOutpostPieces::addPieces(StructureManager&, BlockPos const&, Rotation const&, std::vector<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> >, std::allocator<std::unique_ptr<StructurePiece, std::default_delete<StructurePiece> > > >&, Random&, Dimension&)
PillagerOutpostPieces::PillagerOutpostPiece::PillagerOutpostPiece(StructureManager&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, BlockPos const&, Rotation, float, bool, Dimension&)
PillagerOutpostPieces::PillagerOutpostPiece::_loadTemplate()
PillagerOutpostPieces::PillagerOutpostPiece::PillagerOutpostPiece(StructureManager&)
PillagerOutpostPieces::PillagerOutpostPiece::postProcess(BlockSource*, Random&, BoundingBox const&)
PillagerOutpostPieces::PillagerOutpostPiece::_handleDataMarker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, BlockPos const&, BlockSource&, Random&, BoundingBox const&)
PillagerOutpostPieces::PillagerOutpostPiece::postProcessMobsAt(BlockSource*, Random&, BoundingBox const&)
PillagerOutpostPieces::PillagerOutpostPiece::_addMobsFromPositions(BoundingBox const&, ActorDefinitionIdentifier const&, BlockSource&, std::vector<BlockPos, std::allocator<BlockPos> > const&)
PillagerOutpostPieces::PillagerOutpostPiece::addHardcodedSpawnAreas(LevelChunk&) const
