PillagerOutpostFeature::PillagerOutpostFeature(unsigned int)
PillagerOutpostFeature::getNearestGeneratedFeature(Dimension&, BiomeSource&, BlockPos const&, BlockPos&)
PillagerOutpostFeature::isFeatureChunk(BiomeSource const&, Random&, ChunkPos const&, unsigned int)
PillagerOutpostFeature::initMobSpawnTypes(HardcodedSpawnAreaRegistry&)
PillagerOutpostFeature::createStructureStart(Dimension&, BiomeSource&, Random&, ChunkPos const&)
PillagerOutpostStart::PillagerOutpostStart()
PillagerOutpostStart::postProcess(BlockSource*, Random&, BoundingBox const&)
PillagerOutpostStart::_fillWithSupportBlock(BlockPos const&, BlockSource*, BoundingBox const&, Block const&)
PillagerOutpostStart::PillagerOutpostStart(Dimension&, Random&, int, int)
PillagerOutpostStart::createOutpost(Dimension&, Random&, int, int)
