ShipwreckFeature::ShipwreckFeature(OceanMonumentFeature&, unsigned int)
ShipwreckFeature::getNearestGeneratedFeature(Dimension&, BiomeSource&, BlockPos const&, BlockPos&)
ShipwreckFeature::isFeatureChunk(BiomeSource const&, Random&, ChunkPos const&, unsigned int)
ShipwreckFeature::isShipwreckBeached(int)
ShipwreckFeature::createStructureStart(Dimension&, BiomeSource&, Random&, ChunkPos const&)
ShipwreckStart::ShipwreckStart()
ShipwreckStart::ShipwreckStart(BiomeSource&, Random&, int, int)
ShipwreckPiece::ShipwreckPiece(int, int, bool)
ShipwreckPiece::postProcess(BlockSource*, Random&, BoundingBox const&)
