StrongholdFeature::StrongholdFeature(VillageFeature*, unsigned int)
StrongholdFeature::isFeatureChunk(BiomeSource const&, Random&, ChunkPos const&, unsigned int)
StrongholdFeature::generatePositions(Random&, BiomeSource const&, unsigned int)
StrongholdFeature::_hasAdditionalStronghold(unsigned int, Random&, ChunkPos const&)
StrongholdFeature::getNearestGeneratedFeature(Dimension&, BiomeSource&, BlockPos const&, BlockPos&)
StrongholdFeature::_getNearestStronghold(unsigned int, BlockPos const&, BlockPos&)
StrongholdFeature::createStructureStart(Dimension&, BiomeSource&, Random&, ChunkPos const&)
StrongholdFeature::getGuesstimatedFeaturePositions()
StrongholdFeature::_isBeyondMinimumDistance(ChunkPos const&)
StrongholdFeature::_generateStronghold(unsigned int, ChunkPos const&)
StrongholdFeature::_getCenterOfGrid(ChunkPos const&)
StrongholdFeature::_getGridCoordinates(ChunkPos const&)
StrongholdFeature::_isPregeneratedStrongholdHere(GridPos const&, ChunkPos&)
StrongholdFeature::_hasStrongholds(std::vector<StrongholdFeature::StrongholdResult, std::allocator<StrongholdFeature::StrongholdResult> > const&)
StrongholdFeature::_closestChunkPos(ChunkPos const&, std::vector<StrongholdFeature::StrongholdResult, std::allocator<StrongholdFeature::StrongholdResult> >&)
StrongholdFeature::_sameGrid(GridPos const&, GridPos const&)
StrongholdFeature::_logStrongholdData(std::vector<StrongholdFeature::StrongholdResult, std::allocator<StrongholdFeature::StrongholdResult> > const&)
StrongholdStart::StrongholdStart(Dimension&, Random&, int, int)
