BaseContainerMenu::BaseContainerMenu(Player&, ContainerType)
BaseContainerMenu::~BaseContainerMenu()
BaseContainerMenu::~BaseContainerMenu()
BaseContainerMenu::setData(int, int)
BaseContainerMenu::broadcastChanges()
BaseContainerMenu::_saveLastSlots(Container*)
BaseContainerMenu::distanceCheck(BlockPos const&, float)
BaseContainerMenu::isSlotDirty(int)
BaseContainerMenu::isResultSlot(int)
BaseContainerMenu::getContainerId() const
BaseContainerMenu::setContainerId(ContainerID)
BaseContainerMenu::getContainerType() const
BaseContainerMenu::setContainerType(ContainerType)
BaseContainerMenu::containerContentChanged(int)
BaseContainerMenu::setLastSlot(int, ItemStack const&)
