PatternEntry::PatternEntry(Block const&, std::function<bool (BlockSource&, BlockPos const&, Block const&)>)
BlockPatternBuilder::start(BlockSource&)
BlockPatternBuilder::BlockPatternBuilder(BlockSource&)
BlockPatternBuilder::aisle(int, ...)
BlockPatternBuilder::define(char, Block const&, std::function<bool (BlockSource&, BlockPos const&, Block const&)>)
BlockPatternBuilder::build()
BlockPatternBuilder::_allCharactersMatched()
BlockPatternBuilder::match(BlockPos const&)
BlockPatternBuilder::_fitsBlockPatternEntry(int, int, BlockPos const&, Block const&)
BlockPatternBuilder::match(BlockPos const&, int, int)
BlockPatternBuilder::match(BlockPos const&, int, int, unsigned char, unsigned char)
BlockPatternBuilder::_fitsBlockPatternEntry(int, int, BlockPos const&)
BlockPatternBuilder::replaceBlocks(char, BuildMatch, Block const&, bool)
BlockPatternBuilder::_isAnyPattern(char)
BlockPatternBuilder::_getPattern(int, int)
BlockPatternBuilder::isReadyForMatch()
BlockPatternBuilder::_getBlockPatternEntry(int, int)
BlockPatternBuilder::_fitsAnyPattern(int, int)
