FoliageColor::_index(float, float)
FoliageColor::_getX(float, float)
FoliageColor::_getY(float, float)
FoliageColor::getGrassColor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, float)
FoliageColor::getGrassColor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float)
FoliageColor::getFoliageColor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, float)
FoliageColor::getMapGrassColor(float, float)
FoliageColor::getMapFoliageColor(float, float)
FoliageColor::getGrassColor(float, float)
FoliageColor::getFoliageColor(float, float)
FoliageColor::getEvergreenColor(float, float)
FoliageColor::getMapEvergreenColor(float, float)
FoliageColor::getBirchColor(float, float)
FoliageColor::getMapBirchColor(float, float)
FoliageColor::getDefaultColor()
FoliageColor::_toRGB(int)
FoliageColor::calculateMapGrassColorHelper(BlockSource&, BlockPos const&, BlockPos const&, int&, int&, int&)
FoliageColor::getGrassColor(BlockSource&, BlockPos const&)
FoliageColor::getMapGrassColor(BlockSource&, BlockPos const&)
FoliageColor::_setPalette(mce::Image const&, std::array<int, 65536ul>&)
FoliageColor::setGrassColorPalette(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mce::Image&)
FoliageColor::setFoliageColorPalette(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mce::Image&)
FoliageColor::buildGrassColor(BlockPos const&, BlockPos const&, BlockSource&, Random&)
FoliageColor::getGrassNoise()
