TagSystem::addTag(TagsComponent&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, TagRegistry&)
TagSystem::removeTag(TagsComponent&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, TagRegistry&)
TagSystem::initLevelTagCache(TagsComponent&, Level&)
TagSystem::deregisterTagsFromLevelCache(TagsComponent&, Level&)
TagSystem::synchLevelTagCache(Level&, TagRegistry&)
TagSystem::hasTag(TagsComponent const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, TagRegistry const&)
TagSystem::hasTag(TagsComponent const&, IDType<TagIDType> const&, TagRegistry const&)
TagSystem::getTags[abi:cxx11](TagsComponent const&, TagRegistry&)
TagSystem::removeTrackedTag(TagsComponent&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Level&)
TagSystem::addTrackedTag(TagsComponent&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Level&)
