FurnaceResultContainerController::FurnaceResultContainerController(std::shared_ptr<ContainerModel>)
FurnaceResultContainerController::~FurnaceResultContainerController()
FurnaceResultContainerController::~FurnaceResultContainerController()
FurnaceResultContainerController::isItemAllowed(ItemInstance const&) const
