ShulkerBoxContainerController::ShulkerBoxContainerController(std::shared_ptr<ContainerModel>)
ShulkerBoxContainerController::~ShulkerBoxContainerController()
ShulkerBoxContainerController::~ShulkerBoxContainerController()
ShulkerBoxContainerController::isItemAllowed(ItemInstance const&) const
