TradeIngredientContainerController::TradeIngredientContainerController(std::shared_ptr<ContainerModel>)
TradeIngredientContainerController::isItemAllowed(ItemInstance const&) const
TradeIngredientContainerController::setTradeItem(ItemStack const&)
