getWorkerConfiguration(unsigned int, unsigned int)
createWorkerPool(gsl::basic_string_span<char const, -1l>, WorkerConfiguration const&)
configureThread(ThreadConfiguration const&)
MinecraftWorkerPool::loadWorkerConfigurations(unsigned int, unsigned int)
MinecraftWorkerPool::initializeDefaults()
MinecraftWorkerPool::configureMainThread()
MinecraftWorkerPool::configureServerThread()
MinecraftWorkerPool::createSingletons()
MinecraftWorkerPool::destroySingletons()
