Core::FileSystem::openFile(Core::Path const&, Core::File&, Core::FileOpenMode, Core::FileBufferingMode)
Core::FileSystem::cleanPath_deprecated(Core::PathBuffer<Core::StackString<char, 1024ul> >&, Core::Path const&)
Core::FileSystem::fileExists(Core::Path const&)
Core::FileSystem::deleteFile(Core::Path const&)
Core::FileSystem::getFileSize(Core::Path const&, unsigned long*)
Core::FileSystem::renameFile(Core::Path const&, Core::Path const&)
Core::FileSystem::createEmptyFile(Core::Path const&)
Core::FileSystem::copyFile(Core::Path const&, Core::Path const&)
Core::FileSystem::copyFileWithLimit(Core::Path const&, Core::Path const&)
Core::FileSystem::readFileData(Core::Path const&, std::vector<unsigned char, std::allocator<unsigned char> >&)
Core::FileSystem::createOneDirectory(Core::Path const&)
Core::FileSystem::createOneDirectoryIfNotExisting(Core::Path const&)
Core::FileSystem::createDirectoryRecursively(Core::Path const&)
Core::FileSystem::directoryExists(Core::Path const&)
Core::FileSystem::deleteEmptyDirectory(Core::Path const&)
Core::FileSystem::deleteDirectoryAndContentsRecursively(Core::Path const&)
Core::FileSystem::deleteDirectoryContentsRecursively(Core::Path const&)
Core::FileSystem::renameDirectory(Core::Path const&, Core::Path const&)
Core::FileSystem::iterateOverDirectory(Core::Path const&, Core::DirectoryIterationFlags, std::function<Core::Result (Core::DirectoryIterationItem const&)>)
Core::FileSystem::getDirectoryFiles(std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, Core::Path const&)
Core::FileSystem::getDirectoryFilesRecursively(std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, Core::Path const&)
Core::FileSystem::getDirectoryFilesSizeRecursively(unsigned long&, Core::Path const&)
Core::FileSystem::getDirectoryFilesAllocatedSizeRecursively(unsigned long&, unsigned long&, Core::Path const&)
Core::FileSystem::copyDirectoryAndContentsRecursively(Core::Path const&, Core::Path const&)
Core::FileSystem::copyDirectoryAndContentsRecursivelyWithLimit(Core::Path const&, Core::Path const&)
Core::FileSystem::_getDirectoriesAndFileSizesRecursively(Core::Path const&, std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, std::vector<Core::FileSystem::BasicFileData, std::allocator<Core::FileSystem::BasicFileData> >&)
Core::FileSystem::fileOrDirectoryExists(Core::Path const&)
Core::FileSystem::renameFileOrDirectory(Core::Path const&, Core::Path const&)
Core::FileSystem::getFileOrDirectorySize(Core::Path const&, unsigned long*)
Core::FileSystem::countDirectoryFiles(Core::Path const&, unsigned long*)
Core::FileSystem::isValidPath(Core::Path const&)
Core::FileSystem::isRelativePath(Core::Path const&)
Core::FileSystem::getLastModificationTime(Core::Path const&, long*)
Core::FileSystem::copyTimeAndAccessRights(Core::Path const&, Core::Path const&)
Core::FileSystem::createFlatFile(Core::Path const&, Core::Path const&)
Core::FileSystem::isDirectoryPathAFlatFile(Core::Path const&)
Core::FileSystem::copyFlatFile(Core::Path const&, Core::Path const&, std::vector<Core::ExcludedPath, std::allocator<Core::ExcludedPath> > const&, std::vector<Core::ExcludedPath, std::allocator<Core::ExcludedPath> > const&)
Core::FileSystem::_copyFlatFile(Core::Path const&, Core::Path const&, std::vector<Core::ExcludedPath, std::allocator<Core::ExcludedPath> > const&, std::vector<Core::ExcludedPath, std::allocator<Core::ExcludedPath> > const&)
Core::FileSystem::createDirectoryForFile(Core::Path const&)
Core::FileSystem::getUniqueFilePathForFile(Core::Path const&)
Core::FileSystem::getUniqueFilePathForDirectory(Core::Path const&)
Core::FileSystem::createUniquePathFromSeed(Core::Path const&, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (int)>)
Core::FileSystem::splitPathIntoFullPathSegments[abi:cxx11](Core::Path const&)
Core::FileSystem::readFileData(Core::Path const&, unsigned long, unsigned long, std::vector<unsigned char, std::allocator<unsigned char> >&, unsigned long&)
Core::FileSystem::cleanPathSeparators_deprecated(Core::PathBuffer<Core::StackString<char, 1024ul> >&, Core::Path const&)
Core::FileSystem::checkStorageCorrupt(Core::Path const&)
Core::FileSystem::_copyDirectoryStructure(Core::Path const&, Core::Path const&, std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, Core::FileSystemImpl*)
Core::FileSystem::_copyFilesWithLimit(Core::Path const&, Core::Path const&, std::vector<Core::FileSystem::BasicFileData, std::allocator<Core::FileSystem::BasicFileData> >&, unsigned long&, unsigned long, std::function<Core::Result (Core::Path const&, Core::Path const&, Core::FileSystem::FileTransferProgress&)> const&)
