Core::ZipUtils::getTranslatedZipResult(int)
Core::ZipUtils::getTranslatedUnzipResult(int)
Core::ZipUtils::ZipFileRestrictions::ZipFileRestrictions()
Core::ZipUtils::ZipFileRestrictions::~ZipFileRestrictions()
Core::ZipUtils::ZipFileRestrictions::allowFile(Core::Path const&) const
Core::ZipUtils::ZipFileRestrictions::addForbiddenExtensions(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
Core::ZipUtils::ZipFileRestrictions::addRestrictedExtensions(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
Core::ZipUtils::ZipFileRestrictions::addForbiddenFilenames(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
Core::ZipUtils::ZipSettings::ZipSettings()
Core::ZipUtils::ZipSettings::ZipSettings(Core::ZipUtils::ZipCompressionLevel)
Core::ZipUtils::ZipSettings::~ZipSettings()
Core::ZipUtils::UnzipSettings::UnzipSettings()
Core::ZipUtils::UnzipSettings::~UnzipSettings()
Core::ZipUtils::ZipProgress::ZipProgress()
Core::ZipUtils::ZipProgress::clear()
Core::ZipUtils::ZipProgress::~ZipProgress()
Core::ZipUtils::zip(Core::Path const&, Core::Path const&, Core::ZipUtils::ZipProgress&, bool, Core::ZipUtils::ZipSettings const&)
Core::ZipUtils::zip(std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, Core::Path const&, Core::ZipUtils::ZipProgress&, bool, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (Core::Path)>, Core::ZipUtils::ZipSettings const&)
Core::ZipUtils::unzipInTransaction(Core::Path const&, Core::Path const&, Core::ZipUtils::ZipProgress&, bool, Core::ZipUtils::UnzipSettings const&)
Core::ZipUtils::unzipToFlatFile(Core::Path const&, Core::Path const&, Core::ZipUtils::ZipProgress&, Core::FileBufferingMode, Core::ZipUtils::UnzipSettings const&)
Core::ZipUtils::_zipEncodedPathToUTF8(Core::Path const&)
Core::ZipUtils::getFilenames(Core::Path const&, std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, Core::ZipUtils::UnzipSettings const&)
Core::ZipUtils::exists(Core::Path const&, Core::Path const&)
Core::ZipUtils::readAssetFileZipped[abi:cxx11](Core::Path const&, Core::Path const&)
Core::ZipUtils::ZipProgressList::getCount()
Core::ZipUtils::ZipProgressList::_getSum(std::function<unsigned int (std::shared_ptr<Core::ZipUtils::ZipProgress>)>)
Core::ZipUtils::ZipProgressList::getSkipped()
Core::ZipUtils::ZipProgressList::getTotal()
Core::ZipUtils::ZipProgressList::getProgress()
Core::ZipUtils::ZipProgressList::clear()
Core::ZipUtils::ZipProgressList::createProgress()
