PotionBrewing::Ingredient::Ingredient(Item const&, int)
PotionBrewing::Ingredient::Ingredient(ItemInstance const&)
PotionBrewing::Ingredient::equals(ItemDescriptor const&) const
PotionBrewing::Ingredient::getItemId() const
PotionBrewing::Ingredient::getData() const
PotionBrewing::initPotionBrewing()
PotionBrewing::addContainer(PotionBrewing::Ingredient const&)
PotionBrewing::addChemistryMix(ItemInstance const&, PotionBrewing::Ingredient const&, ItemInstance const&)
PotionBrewing::shutdown()
PotionBrewing::isFuel(ItemDescriptor const&)
PotionBrewing::getFuelValue(ItemDescriptor const&)
PotionBrewing::isIngredient(ItemDescriptor const&)
PotionBrewing::isContainerIngredient(ItemDescriptor const&)
PotionBrewing::isPotionIngredient(ItemDescriptor const&)
PotionBrewing::hasMix(ItemInstance const&, ItemDescriptor const&)
PotionBrewing::hasContainerMix(ItemDescriptor const&, ItemDescriptor const&)
PotionBrewing::hasPotionMix(ItemInstance const&, ItemDescriptor const&)
PotionBrewing::hasChemistryMix(ItemDescriptor const&, ItemDescriptor const&)
PotionBrewing::hasPotionMix(std::shared_ptr<Potion const> const&, ItemDescriptor const&)
PotionBrewing::getChemistryMix(ItemDescriptor const&, ItemDescriptor const&)
PotionBrewing::mix(ItemDescriptor const&, ItemInstance const&)
PotionBrewing::chemistryMixMatches(PotionBrewing::Mix<ItemInstance> const&, ItemDescriptor const&, ItemDescriptor const&)
PotionBrewing::addContainerRecipe(Item const&, PotionBrewing::Ingredient const&, Item const&)
PotionBrewing::addPotionMix(std::shared_ptr<Potion const>, PotionBrewing::Ingredient const&, std::shared_ptr<Potion const> const&)
