CircuitSystem::CircuitSystem()
CircuitSystem::updateDependencies(BlockSource*)
CircuitSystem::evaluate(BlockSource*)
CircuitSystem::_shouldEvaluate(BlockSource*)
CircuitSystem::cacheValues()
CircuitSystem::evaluateComponents(bool)
CircuitSystem::checkLocks()
CircuitSystem::updateBlocks(BlockSource&, BlockPos const&)
CircuitSystem::updateIndividualBlock(BaseCircuitComponent*, BlockPos const&, BlockPos const&, BlockSource&)
CircuitSystem::createComponent(BlockPos const&, unsigned char, std::unique_ptr<BaseCircuitComponent, std::default_delete<BaseCircuitComponent> >)
CircuitSystem::removeComponents(BlockPos const&)
CircuitSystem::setStrength(BlockPos const&, int)
CircuitSystem::getDirection(BlockPos const&)
CircuitSystem::hasDirectPower(BlockPos const&)
CircuitSystem::isAvailableAt(BlockPos const&)
CircuitSystem::getStrength(BlockPos const&)
CircuitSystem::invalidatePos(BlockPos const&)
CircuitSystem::preSetupPoweredBlocks(ChunkPos const&)
CircuitSystem::getChunkPos(BlockSource*, BlockPos const&)
