CircuitSceneGraph::CircuitSceneGraph()
CircuitSceneGraph::~CircuitSceneGraph()
CircuitSceneGraph::getComponent(BlockPos const&, unsigned long)
CircuitSceneGraph::getBaseComponent(BlockPos const&)
CircuitSceneGraph::getFromPendingAdd(BlockPos const&, unsigned long)
CircuitSceneGraph::getFromPendingAdd(BlockPos const&)
CircuitSceneGraph::processPendingAdds()
CircuitSceneGraph::scheduleRelationshipUpdate(BlockPos const&, BaseCircuitComponent*)
CircuitSceneGraph::setPendingAddAsNewlyLoaded()
CircuitSceneGraph::isPendingAdd(BlockPos const&)
CircuitSceneGraph::add(BlockPos const&, std::unique_ptr<BaseCircuitComponent, std::default_delete<BaseCircuitComponent> >)
CircuitSceneGraph::remove(BlockPos const&, BaseCircuitComponent*)
CircuitSceneGraph::removeComponent(BlockPos const&)
CircuitSceneGraph::processPendingRemoves()
CircuitSceneGraph::update(BlockSource*)
CircuitSceneGraph::processPendingUpdates(BlockSource*)
CircuitSceneGraph::removeStaleRelationships()
CircuitSceneGraph::findRelationships(BlockPos const&, BaseCircuitComponent*, BlockSource*)
CircuitSceneGraph::addIfPoweredBlockAt(BlockSource&, BlockPos const&)
CircuitSceneGraph::addPositionToReEvaluate(ChunkPos const&, BlockPos const&)
CircuitSceneGraph::invalidatePos(BlockPos const&)
CircuitSceneGraph::preSetupPoweredBlocks(ChunkPos const&)
CircuitSceneGraph::PendingEntry::PendingEntry(CircuitSceneGraph::PendingEntry&&)
CircuitSceneGraph::PendingEntry::PendingEntry(BlockPos const&, std::unique_ptr<BaseCircuitComponent, std::default_delete<BaseCircuitComponent> >)
CircuitSceneGraph::PendingEntry::PendingEntry(BlockPos const&, BaseCircuitComponent*)
CircuitSceneGraph::PendingEntry::~PendingEntry()
CircuitSceneGraph::PendingEntry::operator=(CircuitSceneGraph::PendingEntry&&)
