ComparatorCapacitor::ComparatorCapacitor()
ComparatorCapacitor::getPoweroutDirection() const
ComparatorCapacitor::getOldStrength()
ComparatorCapacitor::allowConnection(CircuitSceneGraph&, CircuitTrackingInfo const&, bool&)
ComparatorCapacitor::addSource(CircuitSceneGraph&, CircuitTrackingInfo const&, int&, bool&)
ComparatorCapacitor::removeSource(BlockPos const&, BaseCircuitComponent const*)
ComparatorCapacitor::updateDependencies(CircuitSceneGraph&, BlockPos const&)
ComparatorCapacitor::isSubtractMode()
ComparatorCapacitor::setMode(ComparatorCapacitor::Mode)
ComparatorCapacitor::clearAnalogStrength(unsigned char)
ComparatorCapacitor::setAnalogStrength(int, unsigned char)
ComparatorCapacitor::evaluate(CircuitSystem&, BlockPos const&)
ComparatorCapacitor::GetRearStrength()
ComparatorCapacitor::GetSideStrength()
ComparatorCapacitor::cacheValues(CircuitSystem&, BlockPos const&)
