RedstoneTorchCapacitor::RedstoneTorchCapacitor()
RedstoneTorchCapacitor::removeSource(BlockPos const&, BaseCircuitComponent const*)
RedstoneTorchCapacitor::~RedstoneTorchCapacitor()
RedstoneTorchCapacitor::~RedstoneTorchCapacitor()
RedstoneTorchCapacitor::allowConnection(CircuitSceneGraph&, CircuitTrackingInfo const&, bool&)
RedstoneTorchCapacitor::addSource(CircuitSceneGraph&, CircuitTrackingInfo const&, int&, bool&)
RedstoneTorchCapacitor::isHalfPulse()
RedstoneTorchCapacitor::cacheValues(CircuitSystem&, BlockPos const&)
RedstoneTorchCapacitor::FindStrongestStrength(BlockPos const&, CircuitSystem&, bool&)
RedstoneTorchCapacitor::_canIncrementSelfPower()
RedstoneTorchCapacitor::evaluate(CircuitSystem&, BlockPos const&)
RedstoneTorchCapacitor::setOn(bool)
RedstoneTorchCapacitor::getStrength() const
RedstoneTorchCapacitor::updateDependencies(CircuitSceneGraph&, BlockPos const&)
PushCircularReference(std::unordered_map<BlockPos, RedstoneTorchCapacitor*, std::hash<BlockPos>, std::equal_to<BlockPos>, std::allocator<std::pair<BlockPos const, RedstoneTorchCapacitor*> > >&, BlockPos const&, std::queue<RedstoneTorchCapacitor*, std::deque<RedstoneTorchCapacitor*, std::allocator<RedstoneTorchCapacitor*> > >&)
RedstoneTorchCapacitor::resetBurnOutCount()
