TransporterComponent::TransporterComponent()
TransporterComponent::allowConnection(CircuitSceneGraph&, CircuitTrackingInfo const&, bool&)
TransporterComponent::addSource(CircuitSceneGraph&, CircuitTrackingInfo const&, int&, bool&)
TransporterComponent::cacheValues(CircuitSystem&, BlockPos const&)
TransporterComponent::evaluate(CircuitSystem&, BlockPos const&)
