mce::Math::initMth()
mce::Math::sqrt(float)
mce::Math::fastInvSqrt(float)
mce::Math::invSqrt(float)
mce::Math::floor(float)
mce::Math::ceil(float)
mce::Math::cos(mce::Radian)
mce::Math::cos(float)
mce::Math::sin(mce::Radian)
mce::Math::sin(float)
mce::Math::atan(float)
mce::Math::atan2(float, float)
mce::Math::safeIncrement(int&)
mce::Math::fastRandom()
mce::Math::intFloorDiv(int, int)
mce::Math::absDecrease(float, float, float)
mce::Math::wrapRadians(float)
mce::Math::wrapDegrees(mce::Degree)
mce::Math::wrapDegrees(float)
mce::Math::doubleEqualsEpsilon(double, double)
mce::Math::floatEqualsEpsilon(float, float)
mce::Math::wrapRadians(float, float)
mce::Math::clampRotate(mce::Degree, mce::Degree, mce::Degree)
mce::Math::clampRotate(float, float, float)
mce::Math::lerpRotate(mce::Degree, mce::Degree, float)
mce::Math::lerpRotate(float, float, float)
mce::Math::isNan(float)
mce::Math::absMax(float, float)
mce::Math::absMaxSigned(float, float)
mce::Math::clampedLerp(float, float, float)
mce::Math::signum(float)
mce::Math::wrap(float, float)
mce::Math::snapRotationToCardinal(float)
mce::Math::calculatePSNRForRGB(gsl::span<unsigned char, -1l>, gsl::span<unsigned char, -1l>, unsigned int, unsigned int, unsigned int, optional_ref<int>, optional_ref<int>, optional_ref<int>)
mce::Math::calculatePSNRForRGBA(gsl::span<unsigned char, -1l>, gsl::span<unsigned char, -1l>, unsigned int, unsigned int, unsigned int, optional_ref<int>, optional_ref<int>, optional_ref<int>, optional_ref<int>)
mce::Math::remainder(float, float)
mce::Math::hermiteBlend(float)
mce::Math::log2(float)
mce::Math::log2(unsigned int)
mce::Math::degreesDifference(float, float)
mce::Math::degreesDifferenceAbs(float, float)
mce::Math::approach(float, float, float)
mce::Math::approachDegrees(float, float, float)
Util::isPowerOfTwo(unsigned int)
Util::isAligned(unsigned long, unsigned int)
Util::nextHigherPow2(unsigned int)
Util::nextLowerPow2(unsigned int)
Util::highestBitSet(unsigned int)
