mce::MathUtility::interpolateTransforms(glm::tmat4x4<float, (glm::precision)0>&, glm::tmat4x4<float, (glm::precision)0> const&, glm::tmat4x4<float, (glm::precision)0> const&, float)
mce::MathUtility::getBestHorizDirFromViewMatrix(glm::tmat4x4<float, (glm::precision)0> const&)
mce::MathUtility::getRotationFromNegZToVector(glm::tvec3<float, (glm::precision)0> const&)
mce::MathUtility::floatEqualsEpsilon(float, float, float)
mce::MathUtility::rotateVec2(glm::tvec2<float, (glm::precision)0> const&, float)
mce::MathUtility::getBasis(glm::tvec3<float, (glm::precision)0> const&, glm::tvec3<float, (glm::precision)0>&, glm::tvec3<float, (glm::precision)0>&)
mce::MathUtility::getBezier(glm::tvec3<float, (glm::precision)0> const&, glm::tvec3<float, (glm::precision)0> const&, glm::tvec3<float, (glm::precision)0> const&, float)
mce::MathUtility::generateRotationAroundPivotMat(glm::tmat4x4<float, (glm::precision)0> const&, glm::tvec3<float, (glm::precision)0> const&)
mce::MathUtility::generateRotationAroundPivotMat(glm::tquat<float, (glm::precision)0> const&, glm::tvec3<float, (glm::precision)0> const&)
mce::MathUtility::rotatePointAroundPivot(glm::tmat4x4<float, (glm::precision)0> const&, glm::tvec3<float, (glm::precision)0> const&, glm::tvec4<float, (glm::precision)0> const&)
mce::MathUtility::rotatePointAroundPivot(glm::tquat<float, (glm::precision)0> const&, glm::tvec3<float, (glm::precision)0> const&, glm::tvec4<float, (glm::precision)0> const&)
