WorldGenerator::WorldGenerator()
WorldGenerator::~WorldGenerator()
WorldGenerator::~WorldGenerator()
WorldGenerator::getFeatureName(StructureFeatureType)
WorldGenerator::getFeatureId(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
WorldGenerator::addHardcodedSpawnAreas(LevelChunk&)
