BedrockLog::_threadIdString[abi:cxx11]()
BedrockLog::_processIdString[abi:cxx11]()
BedrockLog::_messageIdString[abi:cxx11](int)
BedrockLog::_priorityFilterString(unsigned int)
BedrockLog::_priorityFilterFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
BedrockLog::_areaFilterString(LogAreaID)
BedrockLog::_areaFilterFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
BedrockLog::_constructAreaFilterFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, BedrockLog::LogAreaFilter&)
BedrockLog::_constructAreaFilterStringFromFilter[abi:cxx11](BedrockLog::LogAreaFilter const&)
BedrockLog::_initPriorityFilterMap()
BedrockLog::_initAreaFilterMap()
BedrockLog::_getLog(BedrockLog::LogCategory, BedrockLog::LogChannel)
BedrockLog::initialize()
BedrockLog::update()
BedrockLog::getLogName(BedrockLog::LogCategory, BedrockLog::LogChannel)
BedrockLog::getLogName()
BedrockLog::_openChannel(Core::Path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, BedrockLog::LogCategory, BedrockLog::LogChannel, bool, LogSettingsUpdater*, double)
BedrockLog::createLog(Core::Path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, BedrockLog::LogCategory, std::bitset<3ul>, bool, LogSettingsUpdater*, double)
BedrockLog::flushAllLogs()
BedrockLog::closeLog(BedrockLog::LogCategory)
BedrockLog::closeAllLogs()
BedrockLog::closeAndResetLog(BedrockLog::LogCategory)
BedrockLog::closeAndResetAllLogs()
BedrockLog::log_va(BedrockLog::LogCategory, std::bitset<3ul>, BedrockLog::LogRule, LogAreaID, unsigned int, char const*, int, char const*, __va_list_tag*)
BedrockLog::log(BedrockLog::LogCategory, std::bitset<3ul>, BedrockLog::LogRule, LogAreaID, unsigned int, char const*, int, char const*, ...)
BedrockLog::log(LogAreaID, unsigned int, char const*, int, char const*, ...)
BedrockLog::log_va(LogAreaID, unsigned int, char const*, int, char const*, __va_list_tag*)
BedrockLog::updateLogFilter(BedrockLog::LogCategory, BedrockLog::LogChannel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)
BedrockLog::updateLogSetting(BedrockLog::LogCategory, BedrockLog::LogChannel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
BedrockLog::toggleLogSetting(BedrockLog::LogCategory, BedrockLog::LogChannel, LogSettingsUpdater&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
BedrockLog::updateLogFilter(BedrockLog::LogCategory, BedrockLog::LogChannel, std::unique_ptr<LogSettingsUpdater, std::default_delete<LogSettingsUpdater> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool)
BedrockLog::dumpLogSettings[abi:cxx11](BedrockLog::LogCategory, BedrockLog::LogChannel)
BedrockLog::updateLogFilter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)
BedrockLog::updateLogSetting(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
BedrockLog::toggleLogSetting(LogSettingsUpdater&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
BedrockLog::updateLogFilter(std::unique_ptr<LogSettingsUpdater, std::default_delete<LogSettingsUpdater> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool)
BedrockLog::dumpLogSettings[abi:cxx11]()
