DebugUtils::DEFAULT_ASSERT_HANDLER(char const*, char const*, char const*, bool, int, char const*, char const*, bool)
DebugUtils::REGISTER_ASSERT_TELEMETRY(std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>)
DebugUtils::UNREGISTER_ASSERT_TELEMETRY()
DebugUtils::REGISTER_CRASHED_TELEMETRY(std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)
DebugUtils::UNREGISTER_CRASHED_TELEMETRY()
DebugUtils::_fireAssertTelemetry(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
DebugUtils::fireCrashedTelemetry(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
DebugUtils::PUBLISH_ASSERT_HANDLER(char const*, char const*, char const*, bool, int, char const*, char const*, bool)
DebugUtils::SET_THREAD_NAME(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
DebugUtils::handleAssert(char const*, char const*, char const*, bool, int, char const*, char const*, bool)
