ServerPlayer::ServerPlayer(Level&, PacketSender&, NetworkHandler&, ClientBlobCache::Server::ActiveTransfersManager&, GameType, NetworkIdentifier const&, unsigned char, std::function<void (ServerPlayer&)>, mce::UUID, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<Certificate, std::default_delete<Certificate> >, int)
ServerPlayer::~ServerPlayer()
ServerPlayer::~ServerPlayer()
ServerPlayer::initializeComponents(Actor::InitializationMethod, VariantParameterList const&)
ServerPlayer::stopSleepInBed(bool, bool)
ServerPlayer::knockback(Actor*, int, float, float, float, float, float)
ServerPlayer::die(ActorDamageSource const&)
ServerPlayer::aiStep()
ServerPlayer::tickWorld(Tick const&)
ServerPlayer::updateChunkPublisherView(Vec3 const&, float)
ServerPlayer::_updateNearbyActors()
ServerPlayer::_getReadOnlyChunkCount()
ServerPlayer::recoverR5LostInventoryAndXP()
ServerPlayer::frameUpdate(FrameUpdateContextBase&)
ServerPlayer::normalTick()
ServerPlayer::_getServerPlayerEventCoordinator()
ServerPlayer::isValidTarget(Actor*) const
ServerPlayer::getInventoryMenu()
ServerPlayer::hurtArmor(int)
ServerPlayer::checkFallDamage(float, bool)
ServerPlayer::handleFallDistanceOnServer(float, bool)
ServerPlayer::sendInventory(bool)
ServerPlayer::sendInventoryTransaction(InventoryTransaction const&) const
ServerPlayer::sendComplexInventoryTransaction(std::unique_ptr<ComplexInventoryTransaction, std::default_delete<ComplexInventoryTransaction> >) const
ServerPlayer::sendNetworkPacket(Packet&) const
ServerPlayer::openContainer(BlockPos const&)
ServerPlayer::_nextContainerCounter()
ServerPlayer::_setContainerManager(std::shared_ptr<IContainerManager>)
ServerPlayer::openContainer(ActorUniqueID const&)
ServerPlayer::openFurnace(BlockPos const&)
ServerPlayer::openBlastFurnace(BlockPos const&)
ServerPlayer::openSmoker(BlockPos const&)
ServerPlayer::openBrewingStand(BlockPos const&)
ServerPlayer::openHopper(BlockPos const&)
ServerPlayer::openHopper(ActorUniqueID const&)
ServerPlayer::openDispenser(BlockPos const&, bool)
ServerPlayer::openCommandBlock(BlockPos const&)
ServerPlayer::openCommandBlockMinecart(ActorUniqueID const&)
ServerPlayer::openBeacon(BlockPos const&)
ServerPlayer::openHorseInventory(ActorUniqueID const&)
ServerPlayer::openTrading(ActorUniqueID const&, bool)
ServerPlayer::openPortfolio()
ServerPlayer::openNpcInteractScreen(Actor&)
ServerPlayer::openInventory()
ServerPlayer::openAnvil(BlockPos const&)
ServerPlayer::openGrindstone(BlockPos const&)
ServerPlayer::openEnchanter(BlockPos const&)
ServerPlayer::openStructureEditor(BlockPos const&)
ServerPlayer::openLabTable(BlockPos const&)
ServerPlayer::openElementConstructor(BlockPos const&)
ServerPlayer::openCompoundCreator(BlockPos const&)
ServerPlayer::openMaterialReducer(BlockPos const&)
ServerPlayer::deleteContainerManager()
ServerPlayer::doDeleteContainerManager()
ServerPlayer::checkMovementStats(Vec3 const&)
ServerPlayer::handleEntityEvent(ActorEvent, int)
ServerPlayer::selectItem(ItemStack const&, int const&)
ServerPlayer::setPermissions(CommandPermissionLevel)
ServerPlayer::prepareRegion(ChunkSource&)
ServerPlayer::findClientChunkRadius(unsigned int) const
ServerPlayer::setClientChunkRadius(unsigned int)
ServerPlayer::setContainerData(IContainerManager&, int, int)
ServerPlayer::slotChanged(IContainerManager&, int, ItemStack const&, ItemStack const&, bool)
ServerPlayer::refreshContainer(IContainerManager&)
ServerPlayer::displayLocalizableMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
ServerPlayer::displayTextObjectMessage(TextObjectRoot const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ServerPlayer::displayWhisperMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ServerPlayer::disconnect()
ServerPlayer::setPlayerInput(float, float, bool, bool)
ServerPlayer::setArmor(ArmorSlot, ItemStack const&)
ServerPlayer::canChangeDimensions() const
ServerPlayer::changeDimension(AutomaticID<Dimension, int>, bool)
ServerPlayer::changeDimensionWithCredits(AutomaticID<Dimension, int>)
ServerPlayer::setPlayerGameType(GameType)
ServerPlayer::sendMobEffectPackets()
ServerPlayer::_getViewDistanceDeterminismBufferRadius() const
ServerPlayer::_scanForNearbyActors()
ServerPlayer::_removeNearbyEntities()
ServerPlayer::onEffectAdded(MobEffectInstance&)
ServerPlayer::onEffectUpdated(MobEffectInstance const&)
ServerPlayer::onEffectRemoved(MobEffectInstance&)
ServerPlayer::isPositionRelevant(AutomaticID<Dimension, int>, BlockPos const&)
ServerPlayer::isEntityRelevant(Actor const&)
ServerPlayer::getControllingPlayer() const
ServerPlayer::suspendRegion()
ServerPlayer::destroyRegion()
ServerPlayer::onSuspension()
ServerPlayer::isTeacher() const
ServerPlayer::setTeacher()
ServerPlayer::isHostingPlayer() const
ServerPlayer::isLoading() const
ServerPlayer::isPlayerInitialized() const
ServerPlayer::setLocalPlayerAsInitialized()
ServerPlayer::load(CompoundTag const&, DataLoadHelper&)
ServerPlayer::getPlayerEventCoordinator()
ServerPlayer::onLinkedSlotsChanged()
ServerPlayer::setLostDataTag(std::unique_ptr<CompoundTag, std::default_delete<CompoundTag> >)
ServerPlayer::getMoveInputHandler()
ServerPlayer::getServerMoveInputHandler()
ServerPlayer::getInputMode() const
ServerPlayer::setInputMode(InputMode const&)
ServerPlayer::getPlayMode() const
ServerPlayer::setPlayMode(ClientPlayMode const&)
ServerPlayer::checkCheating(Vec3 const&)
ServerPlayer::reportMovementTelemetry(MovementEventType)
