safeGetItemId(ItemStack const&)
safeGetItemAuxId(ItemStack const&)
getEdition[abi:cxx11]()
getStatusCode(Json::Value const&)
MinecraftEventing::MinecraftEventing(Core::Path const&)
MinecraftEventing::init()
MinecraftEventing::init(Social::IUserManager&)
MinecraftEventing::updatePrimaryLocalUserId(unsigned int const&)
MinecraftEventing::updateIsLegacyPlayer(bool)
MinecraftEventing::updateIsTrial(bool) const
MinecraftEventing::updateEditionType()
MinecraftEventing::~MinecraftEventing()
MinecraftEventing::unregisterOptionsObserver()
MinecraftEventing::~MinecraftEventing()
MinecraftEventing::onUserSignIn(Social::XboxLiveUser&)
MinecraftEventing::onUserSignOut(Social::XboxLiveUser&)
MinecraftEventing::getSessionId[abi:cxx11]()
MinecraftEventing::getPlayerSessionId[abi:cxx11]()
MinecraftEventing::fireEventDefaultGameTypeChanged(GameType, GameType)
MinecraftEventing::fireEventGameTypeChanged(Player*, GameType, GameType)
MinecraftEventing::fireEventArmorStandItemEquipped(ArmorStand const&, ItemDescriptor const&)
MinecraftEventing::fireEventArmorStandPosed(ArmorStand const&)
MinecraftEventing::addListener(std::unique_ptr<Social::Events::IEventListener, std::default_delete<Social::Events::IEventListener> >)
MinecraftEventing::registerOptionsObserver(std::shared_ptr<Options>)
MinecraftEventing::setTestRunIdTag(int)
MinecraftEventing::removeTestRunIdTag()
MinecraftEventing::setTestTelemetryTag(char const*)
MinecraftEventing::removeTestTelemetryTag()
MinecraftEventing::stopDebugEventLoggingForAllListeners()
MinecraftEventing::tick()
MinecraftEventing::fireEventHeartbeat()
MinecraftEventing::forceSendEvents()
MinecraftEventing::getEventManager() const
MinecraftEventing::fireEventClientIdCreated(int)
MinecraftEventing::fireEventBehaviorErrored(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
MinecraftEventing::fireEventBehaviorFailed(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
MinecraftEventing::fireEventPlayerMovementSettings(Player*)
MinecraftEventing::fireEventPlayerMovementAnomalyDetected(Player*, MovementEventType, float, float, float, float, float)
MinecraftEventing::fireEventPlayerMovementCorrected(Player*, float, float, bool, float, float, int)
MinecraftEventing::fireEventPOIBlockUsageAttempt(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MinecraftEventing::PoiEventBlockType)
MinecraftEventing::fireEventPOIBlockUsed(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MinecraftEventing::PoiEventBlockType)
MinecraftEventing::fireEventBarrelBlockUsed(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MinecraftEventing::POIBlockInteractionType)
MinecraftEventing::fireEventBellBlockUsed(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
mapOutputTypeToInteractionType(MapOutputType)
MinecraftEventing::fireEventCampfireBlockUsed(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MinecraftEventing::POIBlockInteractionType)
MinecraftEventing::fireEventCartographyBlockUsed(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MapOutputType)
MinecraftEventing::fireEventCauldronBlockUsed(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MinecraftEventing::POIBlockInteractionType)
MinecraftEventing::fireEventComposterBlockUsed(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MinecraftEventing::POIBlockInteractionType)
MinecraftEventing::fireEventGrindstoneBlockUsed(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MinecraftEventing::POIBlockInteractionType)
MinecraftEventing::fireEventLecternBlockUsed(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MinecraftEventing::POIBlockInteractionType)
MinecraftEventing::fireEventBlockBroken(Player*, Block const&, MinecraftEventing::BlockPlacementMethod, int)
MinecraftEventing::fireEventBlockPlaced(Player*, Block const&, bool)
MinecraftEventing::fireEventBlockPlacedByCommand(Block const&, int)
MinecraftEventing::fireEventBlockFound(Player*, BlockPos const&)
MinecraftEventing::fireEventCraftingSessionEnd(Player*)
MinecraftEventing::fireEventCraftingSessionStart(Player*, unsigned int)
MinecraftEventing::fireEventEndOfDay(Player*, Level&)
MinecraftEventing::fireEventItemAcquired(Player*, ItemDescriptor const&, unsigned int, ItemAcquisitionMethod)
MinecraftEventing::fireEventItemEquipped(Player*, ItemInstance const&, int)
MinecraftEventing::fireEventItemCrafted(Player*, ItemInstance const&, bool, bool, bool, int, int, int, bool, bool)
MinecraftEventing::fireEventItemDestroyed(Player*, ItemDescriptor const&, unsigned int)
MinecraftEventing::fireEventItemDropped(Player*, ItemDescriptor const&)
MinecraftEventing::fireEventItemSmelted(Player*, ItemDescriptor const&, ItemDescriptor const&)
MinecraftEventing::fireEventItemUsed(Player*, ItemDescriptor const&, ItemUseMethod)
MinecraftEventing::fireEventItemEnchanted(Player*, ItemDescriptor const&, ItemEnchants const&)
MinecraftEventing::fireEventItemEnchanted(Player*, ItemDescriptor const&, unsigned int, int)
MinecraftEventing::fireEventItemNamed(Player*, ItemDescriptor const&)
MinecraftEventing::fireEventTradeCompleted(Player*, Actor*, ItemDescriptor const&, ItemDescriptor const&, ItemInstance const&, int)
MinecraftEventing::fireEventJukeboxUsed(Player*, ItemDescriptor const&)
MinecraftEventing::fireEventMenuShown(Player*, unsigned int, unsigned int)
MinecraftEventing::fireEventMobKilled(Player*, Actor*, Mob&, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
MinecraftEventing::fireEventBossKilled(Player*, int, long, int)
MinecraftEventing::fireEventEntitySpawned(Player*, int, unsigned int)
MinecraftEventing::fireEventFileTransmissionState(IMinecraftEventing::FileTransmissionDirection, IMinecraftEventing::FileTransmissionState, IMinecraftEventing::FileTransmissionType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, double)
MinecraftEventing::fireEventEntityInteracted(Player*, int, MinecraftEventing::InteractionType, int, unsigned char)
MinecraftEventing::fireEventMobBorn(Player*, int, int, unsigned char)
MinecraftEventing::fireEventAgentCommand(Player&, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventAgentCreated(Player&)
MinecraftEventing::fireEventPlayerTravelled(Player*, float)
MinecraftEventing::fireEventPlayerTeleported(Player*, float, MinecraftEventing::TeleportationCause, int)
MinecraftEventing::fireEventPlayerBounced(Player*, Block const&, int)
MinecraftEventing::fireEventPlayerDied(Player*, int, int, int, bool)
MinecraftEventing::fireEventPlayerSaved(Player*)
MinecraftEventing::fireEventPortalBuilt(Player*, AutomaticID<Dimension, int>)
MinecraftEventing::fireEventPortalUsed(Player*, AutomaticID<Dimension, int>, AutomaticID<Dimension, int>)
MinecraftEventing::fireEventPotionBrewed(Player*, ItemDescriptor const&, unsigned int)
MinecraftEventing::fireEventCauldronUsed(Player*, short, unsigned int, short)
MinecraftEventing::fireEventFishBucketed(Player*, int, int, int, bool)
MinecraftEventing::fireEventSpecialMobBuilt(Player*, Mob&)
MinecraftEventing::fireEventConnectionFailed(IMinecraftEventing::ConnectionFailureReason)
MinecraftEventing::fireEventSignInToXboxLive(Social::XboxLiveUser const&, bool, IMinecraftEventing::SignInStage)
MinecraftEventing::fireEventSignOutOfXboxLive(Social::XboxLiveUser const&)
MinecraftEventing::fireEventSignInEdu(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ADRole, IMinecraftEventing::EduSignInStage, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)
MinecraftEventing::fireEventPopupFiredEdu(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ActiveDirectoryAction)
MinecraftEventing::fireServerConnectionEvent(IMinecraftEventing::ServerConnectionOutcome, unsigned int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireServerConnectionAttemptEvent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventScriptLoaded(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)
MinecraftEventing::fireEventScriptRan(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, bool, bool)
MinecraftEventing::fireEventVehicleExited(Player*, unsigned int, unsigned long)
MinecraftEventing::fireEventCaravanChanged(Mob&, int)
MinecraftEventing::fireEventMobEffectChanged(Mob&, MobEffectInstance const&, MinecraftEventing::ChangeType)
MinecraftEventing::fireEventDwellerDied(Actor&, ActorDamageSource const&, bool)
MinecraftEventing::fireEventDwellerRemoved(Actor&, bool)
MinecraftEventing::fireRaidEvent(Player*, int, int, bool)
MinecraftEventing::fireEventCommandBlockEdited(Player*, BaseCommandBlock const&, bool, CommandBlockMode, bool, bool)
MinecraftEventing::fireEventFixedMarketplaceWorldUsingV2VillagersToUseV1()
MinecraftEventing::_fireStructureBlockAction(IMinecraftEventing::StructureBlockActionType, StructureEditorData const&, bool, StructureTelemetryClientData const*)
MinecraftEventing::fireStructureBlockAction(IMinecraftEventing::StructureBlockActionType, StructureEditorData const&, StructureTelemetryClientData const*)
MinecraftEventing::fireStructureBlockRedstoneActivated(IMinecraftEventing::StructureBlockActionType, StructureEditorData const&, StructureTelemetryClientData const*)
MinecraftEventing::fireStructureBlockLoadedInUnloadedChunks(unsigned int, BlockPos const&, BlockPos const&)
MinecraftEventing::fireEventBookEdited(Player*, ItemDescriptor const&, unsigned int)
MinecraftEventing::fireEventBookImageImported(Player*)
MinecraftEventing::fireEventBookCopied(Player*, ItemInstance const&)
MinecraftEventing::fireEventBookExported(Player*, int, int)
MinecraftEventing::fireEventSignedBookOpened(Player*, bool)
MinecraftEventing::fireEventPatternAdded(Player*, ItemInstance const&)
MinecraftEventing::fireEventPatternRemoved(Player*, int, int, int, int, int)
MinecraftEventing::fireEventWorldGenerated(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LevelSettings const&, bool)
MinecraftEventing::_generateWorldSessionId()
MinecraftEventing::fireEventWorldLoaded(Player*, Level&, ResourcePackManager&, ResourcePacksInfoData&)
MinecraftEventing::fireEventWorldUnloaded(Player*, LevelData const&, unsigned int)
MinecraftEventing::fireEventAchievementReceived(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventAwardAchievement(Player*, MinecraftEventing::AchievementIds)
MinecraftEventing::fireEventAwardTrophy(Player const*, unsigned int)
MinecraftEventing::fireEventSetValidForAchievements(Player*, bool)
MinecraftEventing::fireEventMultiplayerRoundStart(Player*, Level&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, Realms::World const&)
MinecraftEventing::fireEventMultiplayerRoundEnd(Player*, int)
MinecraftEventing::fireEventSlashCommandExecuted(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventCaravanChanged(Player*, int, int)
MinecraftEventing::fireEventMultiplayerConnectionStateChanged(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventStartWorld(IMinecraftEventing::NetworkType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Social::MultiplayerServiceIdentifier)
MinecraftEventing::fireEventJoinCanceled(LoadingState)
MinecraftEventing::_getUserXUID[abi:cxx11](unsigned int) const
MinecraftEventing::_getUserManagerConst() const
MinecraftEventing::fireEventFirstTimeClientOpen()
MinecraftEventing::fireEventStartClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
MinecraftEventing::fireEventAppPaused()
MinecraftEventing::fireEventAppUnpaused()
MinecraftEventing::fireEventAppSuspended(bool)
MinecraftEventing::fireEventAppResumed()
MinecraftEventing::fireEventAppConfigurationChanged()
MinecraftEventing::fireEventIAPPurchaseAttempt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Offer&, PurchasePath)
MinecraftEventing::fireEventIAPPurchaseResolved(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Offer&, IMinecraftEventing::PurchaseResult, PurchasePath)
MinecraftEventing::fireEventIAPRedeemAttempt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, PurchasePath)
MinecraftEventing::fireEventIAPRedeemResolved(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, IMinecraftEventing::PurchaseResult, PurchasePath)
MinecraftEventing::fireEventPurchaseAttempt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, IMinecraftEventing::StoreType, PurchasePath)
MinecraftEventing::fireEventPurchaseResolved(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, IMinecraftEventing::StoreType, IMinecraftEventing::PurchaseResult, PurchasePath)
MinecraftEventing::fireEventPurchaseGameAttempt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventTrialDeviceIdCorrelation(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPushNotificationPermission(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPushNotificationReceived(PushNotificationMessage const&)
MinecraftEventing::fireEventPushNotificationOpened(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventHardwareInfo()
MinecraftEventing::fireEventOnSuccessfulClientLogin(Level const*)
MinecraftEventing::fireEventGameSessionStart(Player*, IClientInstance&, Level&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
MinecraftEventing::fireEventWorldFilesListed(unsigned long, unsigned long, unsigned long, unsigned long)
MinecraftEventing::fireEventStorage(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventStorageReport(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPerformanceMetrics(ProfilerLiteTelemetry const&)
MinecraftEventing::fireEventOptionsUpdated(std::shared_ptr<Options>, InputMode, bool)
MinecraftEventing::fireEventChatSettingsUpdated(Player const*, std::vector<Social::Events::Property, std::allocator<Social::Events::Property> > const&) const
MinecraftEventing::fireEventControlRemappedByPlayer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RawInputType, int) const
MinecraftEventing::fireEventDifficultySet(Difficulty, Difficulty)
MinecraftEventing::fireEventGameRulesUpdated(bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventGameRulesUpdated(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventGameRulesUpdated(float, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventGameRulesLoaded(Player*, GameRules const&)
MinecraftEventing::fireCurrentInputUpdated(IClientInstance const&)
MinecraftEventing::fireEventSplitScreenUpdated(IClientInstance const&)
MinecraftEventing::fireEventScreenChanged(unsigned int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)
MinecraftEventing::fireEventPopupClosed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
MinecraftEventing::fireEventGameplayTipShown(int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventOfferRated(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, double)
MinecraftEventing::fireEventNewContentCheckCompleted(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
MinecraftEventing::fireEventHowToPlayTopicChanged(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, InputMode)
MinecraftEventing::fireEventApiInit(float, unsigned long)
MinecraftEventing::fireEventPlayerTransform(Player&)
MinecraftEventing::fireEventPlayerJoin(Player&)
MinecraftEventing::fireEventPlayerLeave(Player&)
MinecraftEventing::fireEventPlayerMessageSay(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPlayerMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPlayerMessageTell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPlayerMessageChat(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPlayerMessageMe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPlayerMessageTitle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventChunkLoaded(LevelChunk&)
MinecraftEventing::fireEventChunkUnloaded(LevelChunk&)
MinecraftEventing::fireEventChunkChanged(LevelChunk&)
MinecraftEventing::fireEventItemInteracted(Player*, ItemInstance const&, MinecraftEventing::ItemInteractMethod)
MinecraftEventing::fireEventUploadSkin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventLicenseCheck(bool, ExtraLicenseData&)
MinecraftEventing::fireEventIAPPurchaseFailure(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, PurchaseInfo const&)
MinecraftEventing::fireEventPurchaseFailureDetails(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventIncognitoFailure(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventDeviceAccountFailure(IMinecraftEventing::SignInStage, IMinecraftEventing::DeviceAccountFailurePhase, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventDeviceAccountSuccess(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventEntitlementListInfo(std::vector<ContentIdentity, std::allocator<ContentIdentity> >&, bool)
MinecraftEventing::fireEventStorePromotionNotification(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPromotionNotificationClicked(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventStoreOfferClicked(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventStoreSearch(StoreSearchTelemetryData const&)
MinecraftEventing::fireEventSearchItemSelected(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)
MinecraftEventing::fireEventVideoPlayed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventUgcDownloadStarted(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventUgcDownloadCompleted(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
MinecraftEventing::prepEventSearchCatalogRequest(SearchRequestTelemetry const&)
MinecraftEventing::fireEventSearchCatalogRequest(SearchRequestTelemetry const&)
MinecraftEventing::fireEventTreatmentsSet(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
MinecraftEventing::fireEventTreatmentsCleared()
MinecraftEventing::fireEventSetMultiplayerCorrelationId(Player*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPackPlayed(PackInstance const&, unsigned int)
MinecraftEventing::fireEventRespondedToAcceptContent(ResourcePacksInfoData const&, bool)
MinecraftEventing::fireEventNewUserPackDetected(PackManifest const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
MinecraftEventing::_fireEventPackImportStage(ResourcePack const*, PackManifest const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)
MinecraftEventing::fireEventPackImportStarted(PackManifest const&)
MinecraftEventing::fireEventPackHashChanged(PackManifest const&)
MinecraftEventing::fireEventPackImportedCompleted(ResourcePack const*, PackManifest const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::addBehaviorPackData(Social::Events::Event&, BehaviorPackContents const&)
MinecraftEventing::addResourcePackData(Social::Events::Event&, ResourcePackContents const&)
MinecraftEventing::fireEventPackUpgradeAttempt(PackManifest const&, PackReport const&)
MinecraftEventing::fireEventStackLoaded(StackStats const&)
MinecraftEventing::firePackSettingsEvent(PackSettings const&, PackManifest const&)
MinecraftEventing::fireEventTreatmentPackApplied(PackManifest const&)
MinecraftEventing::fireEventTreatmentPackDownloaded(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
MinecraftEventing::fireEventTreatmentPackRemoved(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
MinecraftEventing::fireEventContentLogsInWorldSession(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)
MinecraftEventing::fireEventNpcPropertiesUpdated(Actor&, bool)
MinecraftEventing::fireEventBoardTextUpdated(ChalkboardBlockActor&)
MinecraftEventing::fireTextToSpeechToggled(bool, bool)
MinecraftEventing::fireEventEntityDanced(int, int, unsigned char)
MinecraftEventing::fireEventCameraUsed(bool)
MinecraftEventing::fireEventPortfolioExported(int, int)
MinecraftEventing::fireInAppCodeBuilderActivated(IMinecraftEventing::OpenCodeMethod)
MinecraftEventing::fireEventEduiOSPurchaseTransaction(TransactionStatus const&) const
MinecraftEventing::fireCodeCommandButtonPressed()
MinecraftEventing::fireIDESelected(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
MinecraftEventing::fireEventEduResources() const
MinecraftEventing::fireEventEduOptionSet(Option const&) const
MinecraftEventing::fireEventCodeBuilderClosed() const
MinecraftEventing::fireEventWebviewDownload(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, WebviewDownloadInfo const&) const
MinecraftEventing::fireEventEduServiceStatus(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, buffer_span<std::pair<gsl::basic_string_span<char const, -1l>, gsl::basic_string_span<char const, -1l> > >) const
MinecraftEventing::fireEduServiceRequestFailed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, buffer_span<std::pair<gsl::basic_string_span<char const, -1l>, gsl::basic_string_span<char const, -1l> > >) const
MinecraftEventing::fireEventButtonPressed(gsl::basic_string_span<char const, -1l>, buffer_span<std::pair<gsl::basic_string_span<char const, -1l>, gsl::basic_string_span<char const, -1l> > >) const
MinecraftEventing::fireQuickPlayEvent()
MinecraftEventing::fireLibraryButtonPressed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireCourseButtonPressed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireLessonActionTaken(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, IMinecraftEventing::EducationLessonAction)
MinecraftEventing::fireEventWorldExported(long, unsigned long)
MinecraftEventing::fireEventWorldImported(long, unsigned long)
MinecraftEventing::fireGlobalResourcePackCrashRecovery(PackInstance&, mce::UUID, int)
MinecraftEventing::fireEventRealmShared(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, IMinecraftEventing::ShareMode const&, Realms::RealmId const&)
MinecraftEventing::fireEventRealmMemberlistCleared(Realms::RealmId const&, int const&)
MinecraftEventing::fireEventRealmUrlGenerated(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Realms::RealmId const&)
MinecraftEventing::fireEventContentShared(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, IMinecraftEventing::ShareMode const&)
MinecraftEventing::fireEventStructureExport(glTFExportData const&, IMinecraftEventing::ExportOutcome, IMinecraftEventing::ExportStage) const
MinecraftEventing::fireMinecraftVersionLaunched(bool)
MinecraftEventing::fireMinecraftVersionInviteAccepted(bool, unsigned long)
MinecraftEventing::fireDayOneExperienceStateChanged(IMinecraftEventing::DayOneExperienceState, std::optional<unsigned int>, std::optional<unsigned long>)
MinecraftEventing::fireWorldConversionAttemptEvent(Legacy::WorldConversionReport const&)
MinecraftEventing::fireWorldConversionInitiatedEvent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::_addConversionReportData(Social::Events::Event&, mclc::ConversionReport const*)
MinecraftEventing::fireLegacyWorldUploadEvent(Legacy::WorldConversionReport const&, bool, WorldConversionError)
MinecraftEventing::fireEventDevConsoleOpen()
MinecraftEventing::fireEventDevConsoleCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventAssertFailed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
MinecraftEventing::fireEventSessionCrashed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireChatUsedEvent(unsigned int, bool)
MinecraftEventing::fireEventJoinByCode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireRealmConnectionEventStart(IMinecraftEventing::RealmConnectionFlow)
MinecraftEventing::fireRealmConnectionEventRealmAPIRequest(IMinecraftEventing::RealmConnectionFlow)
MinecraftEventing::fireRealmConnectionEventRealmAPIResponse(IMinecraftEventing::RealmConnectionFlow, int)
MinecraftEventing::fireRealmConnectionEventGenericLambdaCalled(IMinecraftEventing::RealmConnectionFlow, IMinecraftEventing::RealmConnectionLambda, IMinecraftEventing::RealmConnectionResult)
MinecraftEventing::fireClubsOpenFeedScreenEvent(IMinecraftEventing::ClubsFeedScreenSource, Realms::RealmId, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
MinecraftEventing::fireClubsEngagementEvent(IMinecraftEventing::ClubsEngagementAction, IMinecraftEventing::ClubsEngagementTargetType, char const*, Realms::RealmId, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
MinecraftEventing::fireEventExperimentalGameplay(bool, bool)
MinecraftEventing::fireEventCopyWorldEducationEnabled()
MinecraftEventing::fireEventRespawn(Player&, int)
MinecraftEventing::fireEventServerRespawnSearchTime(Player&, PlayerRespawnTelemetryData const&)
MinecraftEventing::fireEventUnknownBlockReceived(NewBlockID const&, unsigned short)
MinecraftEventing::fireEventElementConstructorUsed(int, int, IMinecraftEventing::ElementConstructorUseType)
MinecraftEventing::fireEventCompoundCreatorCreated(int, int)
MinecraftEventing::fireEventReducerBlockEntered(ItemDescriptor const&)
MinecraftEventing::fireEventMultiplayerSessionUpdate(Level const*, Player const*)
MinecraftEventing::fireEventLevelDestruct()
MinecraftEventing::fireEventLevelDatLoadFailed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
MinecraftEventing::fireEventClientLeftGameDueToUnrecoverableError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
MinecraftEventing::fireEventWorldHistoryPackSourceMissingDuringUpgrade(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventLabTableCreated(int, int, int)
MinecraftEventing::_getAccountType(std::shared_ptr<Social::User>)
MinecraftEventing::_convertStoreTypeToString[abi:cxx11](IMinecraftEventing::StoreType) const
MinecraftEventing::_convertPurchasePathToString[abi:cxx11](PurchasePath) const
MinecraftEventing::_convertPromotionTypeToString[abi:cxx11](IMinecraftEventing::PromotionType) const
MinecraftEventing::fireEventFloatPropertyList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> > > const&)
MinecraftEventing::fireEventPetDied(Player*, bool, Actor*, ActorType, unsigned int)
MinecraftEventing::fireEventPersonaItemPreviewed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int, IMinecraftEventing::PromotionType, bool, IMinecraftEventing::StoreType)
MinecraftEventing::fireEventPersonaSkinChanged(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
MinecraftEventing::fireEventPersonaAvatarUpdated(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<bool, std::allocator<bool> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
MinecraftEventing::fireEventPersonaAvatarsListed(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
MinecraftEventing::fireEventPersonaInitalizationEvent(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPersonaGeneralError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPersonaLoadingPieces(unsigned int, double)
MinecraftEventing::fireEventPersonaStillLoading(bool, bool, bool, bool, bool, bool, bool, bool)
MinecraftEventing::fireEventPersonaCreationFailed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventPersonaXForgeResponses(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int)
MinecraftEventing::fireEventPersonaCategoryInformation(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::fireEventAccountTransferStateChanged(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, TransferState, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
MinecraftEventing::_addCommonPurchaseEventProperties(Social::Events::Event&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, PurchasePath) const
