Balloon::Balloon(ActorDefinitionGroup*, ActorDefinitionIdentifier const&)
Balloon::_init()
Balloon::isPickable()
Balloon::_hurt(ActorDamageSource const&, int, bool, bool)
Balloon::remove(bool)
Balloon::remove()
Balloon::normalTick()
Balloon::lerpTo(Vec3 const&, Vec2 const&, int)
Balloon::reloadHardcoded(Actor::InitializationMethod, VariantParameterList const&)
