PrimedTnt::PrimedTnt(ActorDefinitionGroup*, ActorDefinitionIdentifier const&)
PrimedTnt::reloadHardcoded(Actor::InitializationMethod, VariantParameterList const&)
PrimedTnt::inheritOwners(Actor*)
PrimedTnt::reloadHardcodedClient(Actor::InitializationMethod, VariantParameterList const&)
PrimedTnt::isPickable()
PrimedTnt::normalTick()
PrimedTnt::getShadowHeightOffs()
PrimedTnt::getSourceUniqueID() const
PrimedTnt::getOwnerEntityType()
PrimedTnt::teleportTo(Vec3 const&, bool, int, int)
PrimedTnt::_hurt(ActorDamageSource const&, int, bool, bool)
PrimedTnt::addAdditionalSaveData(CompoundTag&)
PrimedTnt::readAdditionalSaveData(CompoundTag const&, DataLoadHelper&)
