ClacksServer::ClacksServer(DedicatedServer&, NetworkAddress const&, ServerInstance&, PermissionsFile&, WhitelistFile&, ServerMetricsImpl&)
ClacksServer::run()
ClacksServer::~ClacksServer()
ClacksServer::stop()
ClacksServer::~ClacksServer()
ClacksServer::listPlayer(grpc::ServerContext*, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::PlayerList*)
ClacksServer::kick(grpc::ServerContext*, com::mojang::clacks::protocol::PlayerAndMessage const*, com::mojang::clacks::protocol::Empty*)
ClacksServer::say(grpc::ServerContext*, com::mojang::clacks::protocol::Message const*, com::mojang::clacks::protocol::Empty*)
ClacksServer::changeSettings(grpc::ServerContext*, com::mojang::clacks::protocol::Settings const*, com::mojang::clacks::protocol::Empty*)
ClacksServer::reloadPermissions(grpc::ServerContext*, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty*)
ClacksServer::reloadOps(grpc::ServerContext*, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty*)
ClacksServer::reloadWhitelist(grpc::ServerContext*, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty*)
ClacksServer::saveHold(grpc::ServerContext*, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty*)
ClacksServer::saveQuery(grpc::ServerContext*, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::SaveQueryResult*)
ClacksServer::saveResume(grpc::ServerContext*, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty*)
ClacksServer::saveState(grpc::ServerContext*, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::SaveStateResult*)
ClacksServer::stop(grpc::ServerContext*, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty*)
ClacksServer::serverStarted(grpc::ServerContext*, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty*)
ClacksServer::subscribeToMetrics(grpc::ServerContext*, com::mojang::clacks::protocol::Empty const*, grpc::ServerWriter<com::mojang::clacks::protocol::MetricReport>*)
