ResetEventObj::ResetEventObj(bool, bool)
ResetEventObj::set()
ResetEventObj::reset()
ResetEventObj::wait()
ResetEventObj::wait_until(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)
ResetEventObj::wait_for(std::chrono::duration<long, std::ratio<1l, 1000l> > const&)
