Recipes::clearRecipes()
Recipes::init(ResourcePackManager&)
Recipes::loadRecipes(ResourcePackManager&)
Recipes::_addMapRecipes()
Recipes::addShapelessRecipe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ItemInstance const&, std::vector<Recipes::Type, std::allocator<Recipes::Type> > const&, std::vector<Util::HashString, std::allocator<Util::HashString> > const&, int, std::function<std::unique_ptr<ShapelessRecipe, std::default_delete<ShapelessRecipe> > (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<RecipeIngredient, std::allocator<RecipeIngredient> > const&, std::vector<ItemInstance, std::allocator<ItemInstance> > const&, Util::HashString)>)
Recipes::addShulkerBoxRecipe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, ItemInstance const&, std::vector<Recipes::Type, std::allocator<Recipes::Type> > const&, std::vector<Util::HashString, std::allocator<Util::HashString> > const&)
Recipes::addShapedRecipe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ItemInstance const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<Recipes::Type, std::allocator<Recipes::Type> > const&, std::vector<Util::HashString, std::allocator<Util::HashString> > const&, int, std::function<std::unique_ptr<ShapedRecipe, std::default_delete<ShapedRecipe> > (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, std::vector<RecipeIngredient, std::allocator<RecipeIngredient> > const&, std::vector<ItemInstance, std::allocator<ItemInstance> > const&, Util::HashString)>)
Recipes::addShapedRecipe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ItemInstance const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<Recipes::Type, std::allocator<Recipes::Type> > const&, std::vector<Util::HashString, std::allocator<Util::HashString> > const&, int, std::function<std::unique_ptr<ShapedRecipe, std::default_delete<ShapedRecipe> > (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, std::vector<RecipeIngredient, std::allocator<RecipeIngredient> > const&, std::vector<ItemInstance, std::allocator<ItemInstance> > const&, Util::HashString)>)
Recipes::addShapedRecipe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ItemInstance const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<Recipes::Type, std::allocator<Recipes::Type> > const&, std::vector<Util::HashString, std::allocator<Util::HashString> > const&, int, std::function<std::unique_ptr<ShapedRecipe, std::default_delete<ShapedRecipe> > (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, std::vector<RecipeIngredient, std::allocator<RecipeIngredient> > const&, std::vector<ItemInstance, std::allocator<ItemInstance> > const&, Util::HashString)>)
Recipes::_loadIngredientFromJson(Json::Value const&) const
Recipes::_itemInstanceFromIngredient(RecipeIngredient const&) const
Recipes::loadRecipe(Json::Value const&)
Recipes::addFurnaceRecipeAuxData(ItemInstance const&, ItemInstance const&, std::vector<Util::HashString, std::allocator<Util::HashString> > const&)
Recipes::addShapedRecipe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<ItemInstance, std::allocator<ItemInstance> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<Recipes::Type, std::allocator<Recipes::Type> > const&, std::vector<Util::HashString, std::allocator<Util::HashString> > const&, int, std::function<std::unique_ptr<ShapedRecipe, std::default_delete<ShapedRecipe> > (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, std::vector<RecipeIngredient, std::allocator<RecipeIngredient> > const&, std::vector<ItemInstance, std::allocator<ItemInstance> > const&, Util::HashString)>)
Recipes::getFurnaceRecipeResult(ItemInstance const&, Util::HashString const&) const
Recipes::addShapedRecipe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ItemInstance const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<Recipes::Type, std::allocator<Recipes::Type> > const&, std::vector<Util::HashString, std::allocator<Util::HashString> > const&, int, std::function<std::unique_ptr<ShapedRecipe, std::default_delete<ShapedRecipe> > (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, std::vector<RecipeIngredient, std::allocator<RecipeIngredient> > const&, std::vector<ItemInstance, std::allocator<ItemInstance> > const&, Util::HashString)>)
Recipes::Shape(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Recipes::Shape(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Recipes::Shape(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Recipes::addSingleIngredientRecipeItem(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ItemInstance const&, RecipeIngredient const&, std::vector<Util::HashString, std::allocator<Util::HashString> > const&)
Recipes::addDirectShapedRecipe(std::unique_ptr<ShapedRecipe, std::default_delete<ShapedRecipe> >)
Recipes::_addItemRecipe(std::unique_ptr<Recipe, std::default_delete<Recipe> >)
Recipes::addMultiRecipe(std::unique_ptr<MultiRecipe, std::default_delete<MultiRecipe> >)
Recipes::addDirectShapelessRecipe(std::unique_ptr<ShapelessRecipe, std::default_delete<ShapelessRecipe> >)
Recipes::~Recipes()
Recipes::getRecipeFor(ItemInstance const&, Util::HashString const&) const
Recipes::getAllRecipesFor(ItemInstance const&, Util::HashString const&) const
Recipes::addRepairItemRecipe(std::unique_ptr<RepairItemRecipe, std::default_delete<RepairItemRecipe> >)
Recipes::getRecipes[abi:cxx11](Util::HashString const&) const
Recipes::getRecipesAllTags[abi:cxx11]() const
Recipes::addRecipeListener(std::weak_ptr<bool>, std::function<void ()>)
Recipes::removeRecipeListener(std::weak_ptr<bool>)
Recipes::notifyRecipeListeners()
