leveldb::EncodeFixed32(char*, unsigned int)
leveldb::EncodeFixed64(char*, unsigned long)
leveldb::PutFixed32(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned int)
leveldb::PutFixed64(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned long)
leveldb::EncodeVarint32(char*, unsigned int)
leveldb::PutVarint32(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned int)
leveldb::EncodeVarint64(char*, unsigned long)
leveldb::PutVarint64(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned long)
leveldb::PutLengthPrefixedSlice(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, leveldb::Slice const&)
leveldb::VarintLength(unsigned long)
leveldb::GetVarint32PtrFallback(char const*, char const*, unsigned int*)
leveldb::GetVarint32(leveldb::Slice*, unsigned int*)
leveldb::GetVarint64Ptr(char const*, char const*, unsigned long*)
leveldb::GetVarint64(leveldb::Slice*, unsigned long*)
leveldb::GetLengthPrefixedSlice(char const*, char const*, leveldb::Slice*)
leveldb::GetLengthPrefixedSlice(leveldb::Slice*, leveldb::Slice*)
