ScriptServerContext::ScriptServerContext()
ScriptServerContext::isValid() const
ScriptServerContext::reset()
ScriptServerContext::validate()
MinecraftServerScriptEngine::MinecraftServerScriptEngine(ServerInstance&)
MinecraftServerScriptEngine::~MinecraftServerScriptEngine()
MinecraftServerScriptEngine::~MinecraftServerScriptEngine()
MinecraftServerScriptEngine::setupInterface()
MinecraftServerScriptEngine::onServerLevelInitialized(ServerInstance&, Level&)
MinecraftServerScriptEngine::_queueResourcePackScripts(ResourcePackManager&)
MinecraftServerScriptEngine::onServerUpdateStart(ServerInstance&)
MinecraftServerScriptEngine::_setupContext(Minecraft&, PacketSender&, entt::Registry<unsigned int>&)
MinecraftServerScriptEngine::onServerUpdateEnd(ServerInstance&)
MinecraftServerScriptEngine::onServerThreadStarted(ServerInstance&)
MinecraftServerScriptEngine::_initializeServer(Level&, NetworkHandler&)
MinecraftServerScriptEngine::onLeaveGameDone(ServerInstance&)
MinecraftServerScriptEngine::_unregisterEventListeners(Level*, NetworkHandler&)
MinecraftServerScriptEngine::onLevelTick()
MinecraftServerScriptEngine::_registerEventListeners(Level&, NetworkHandler&)
MinecraftServerScriptEngine::executeCommand(ScriptCommand const&)
MinecraftServerScriptEngine::_handleError(ScriptApi::ScriptReportItem const&)
MinecraftServerScriptEngine::_handleWarning(ScriptApi::ScriptReportItem const&)
MinecraftServerScriptEngine::_helpRegisterSystemCallbacks(ScriptApi::ScriptObjectHandle const&)
MinecraftServerScriptEngine::_registerSystemObjects(ScriptApi::ScriptObjectHandle const&)
