ProjectileFactory::ProjectileFactory(Level&)
ProjectileFactory::initFactory()
ProjectileFactory::shutdown()
ProjectileFactory::shootProjectileFromDefinition(ActorDefinitionIdentifier const&, Mob*, Vec3)
ProjectileFactory::createSubcomponent(Json::Value&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
