Guardian::Guardian(ActorDefinitionGroup*, ActorDefinitionIdentifier const&)
Guardian::reloadHardcoded(Actor::InitializationMethod, VariantParameterList const&)
Guardian::registerLoopingSounds()
Guardian::reloadHardcodedClient(Actor::InitializationMethod, VariantParameterList const&)
Guardian::~Guardian()
Guardian::~Guardian()
Guardian::addAdditionalSaveData(CompoundTag&)
Guardian::isElder() const
Guardian::readAdditionalSaveData(CompoundTag const&, DataLoadHelper&)
Guardian::setElder(bool)
Guardian::getAttackDuration()
Guardian::setElderGhost()
Guardian::getAmbientSoundPostponeTicks()
Guardian::makeStepSound()
Guardian::getWalkTargetValue(BlockPos const&)
Guardian::aiStep()
Guardian::getTargetEntity() const
Guardian::getAttackAnimationScale(float)
Guardian::getTailAnimation(float)
Guardian::getSpikesAnimation(float)
Guardian::isDarkEnoughToSpawn() const
Guardian::_hurt(ActorDamageSource const&, int, bool, bool)
Guardian::_onSizeUpdated()
Guardian::isElderGhost() const
Guardian::setAttackTime(int)
Guardian::getEyeTarget()
Guardian::getMoveEyeVector()
Guardian::checkSpawnRules(bool)
Guardian::setTarget(Actor*)
Guardian::getMaxHeadXRot()
