PigZombie::PigZombie(ActorDefinitionGroup*, ActorDefinitionIdentifier const&)
PigZombie::normalTick()
PigZombie::checkSpawnRules(bool)
PigZombie::addAdditionalSaveData(CompoundTag&)
PigZombie::readAdditionalSaveData(CompoundTag const&, DataLoadHelper&)
PigZombie::findAttackTarget()
PigZombie::_hurt(ActorDamageSource const&, int, bool, bool)
PigZombie::_alert(Mob&)
PigZombie::getAttackTime()
