Core::FileImpl::getNumFiles()
Core::FileImpl::FileImpl(Core::FileSystemImpl*, Core::FileOpenMode)
Core::FileImpl::~FileImpl()
Core::FileImpl::~FileImpl()
Core::FileImpl::setLoggingEnabled(bool)
Core::FileImpl::getLoggingEnabled() const
Core::FileImpl::getTransaction()
Core::FileImpl::getPath[abi:cxx11]() const
Core::FileImpl::getBlockSize() const
Core::FileImpl::isOpen()
Core::FileImpl::getOpenMode() const
Core::FileImpl::close()
Core::FileImpl::read(void*, unsigned long, unsigned long*)
Core::FileImpl::_readOperation(Core::Result&&, unsigned long)
Core::FileImpl::readExactly(void*, unsigned long)
Core::FileImpl::skip(unsigned long)
Core::FileImpl::readAtPosition(unsigned long, void*, unsigned long, unsigned long*)
Core::FileImpl::getPosition(unsigned long*)
Core::FileImpl::setPosition(unsigned long)
Core::FileImpl::write(void const*, unsigned long)
Core::FileImpl::_writeOperation(Core::Result&&, unsigned long)
Core::FileImpl::flush()
Core::FileImpl::getSize(unsigned long*)
Core::FileImpl::getRemainingSize(unsigned long*)
Core::FileImpl::notifyChangeInFileSize(long, long)
