Core::FileSystemImpl::getGlobalStats()
Core::FileSystemImpl::FileSystemImpl(Core::FileAccessType, std::shared_ptr<Core::FileStorageArea>, std::shared_ptr<Core::FlatFileManifestTracker>)
Core::FileSystemImpl::~FileSystemImpl()
Core::FileSystemImpl::_isTransactionEnded() const
Core::FileSystemImpl::~FileSystemImpl()
Core::FileSystemImpl::getAccessType() const
Core::FileSystemImpl::getStorageArea()
Core::FileSystemImpl::setLoggingEnabled(bool)
Core::FileSystemImpl::getLoggingEnabled() const
Core::FileSystemImpl::enumerateFiles(std::function<void (Core::FileImpl*)> const&)
Core::FileSystemImpl::commit()
Core::FileSystemImpl::openFile(std::unique_ptr<Core::FileImpl, std::default_delete<Core::FileImpl> >&, Core::Path const&, Core::FileOpenMode, Core::FileBufferingMode)
Core::FileSystemImpl::_flatFileOpenFlatFile(std::unique_ptr<Core::FileImpl, std::default_delete<Core::FileImpl> >&, Core::Path const&, Core::Path const&, Core::FileOpenMode, Core::FileBufferingMode)
Core::FileSystemImpl::_readWriteOperation(Core::Result&&, std::function<void (Core::FileStorageArea*)>, unsigned long, unsigned long)
Core::FileSystemImpl::_readOperation(Core::Result&&, unsigned long)
Core::FileSystemImpl::fileExists(Core::Path const&)
Core::FileSystemImpl::deleteFile(Core::Path const&)
Core::FileSystemImpl::getFileSize(Core::Path const&, unsigned long*)
Core::FileSystemImpl::renameFile(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::createEmptyFile(Core::Path const&)
Core::FileSystemImpl::copyFile(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::copyFileWithLimit(Core::Path const&, Core::Path const&, unsigned long, unsigned long&, unsigned long&)
Core::FileSystemImpl::readFileData(Core::Path const&, std::vector<unsigned char, std::allocator<unsigned char> >&)
Core::FileSystemImpl::createOneDirectory(Core::Path const&)
Core::FileSystemImpl::createOneDirectoryIfNotExisting(Core::Path const&)
Core::FileSystemImpl::createDirectoryRecursively(Core::Path const&)
Core::FileSystemImpl::directoryExists(Core::Path const&)
Core::FileSystemImpl::deleteEmptyDirectory(Core::Path const&)
Core::FileSystemImpl::deleteDirectoryAndContentsRecursively(Core::Path const&)
Core::FileSystemImpl::deleteDirectoryContentsRecursively(Core::Path const&)
Core::FileSystemImpl::renameDirectory(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::iterateOverDirectory(Core::Path const&, Core::DirectoryIterationFlags, std::function<Core::Result (Core::DirectoryIterationItem const&)>)
Core::FileSystemImpl::getDirectoryFiles(std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, Core::Path const&)
Core::FileSystemImpl::getDirectoryFilesRecursively(std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, Core::Path const&)
Core::FileSystemImpl::getDirectoryFilesSizeRecursively(unsigned long&, Core::Path const&)
Core::FileSystemImpl::getDirectoryFilesAllocatedSizeRecursively(unsigned long&, unsigned long&, Core::Path const&)
Core::FileSystemImpl::copyDirectoryAndContentsRecursively(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::fileOrDirectoryExists(Core::Path const&)
Core::FileSystemImpl::renameFileOrDirectory(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::createFlatFile(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::isDirectoryPathAFlatFile(Core::Path const&)
Core::FileSystemImpl::copyFlatFile(Core::Path const&, Core::Path const&, std::vector<Core::ExcludedPath, std::allocator<Core::ExcludedPath> > const&, std::vector<Core::ExcludedPath, std::allocator<Core::ExcludedPath> > const&)
Core::FileSystemImpl::getFlatFileManifestTracker() const
Core::FileSystemImpl::getFileOrDirectorySize(Core::Path const&, unsigned long*)
Core::FileSystemImpl::countDirectoryFiles(Core::Path const&, unsigned long*)
Core::FileSystemImpl::getEntryType(Core::Path const&, Core::FileType&)
Core::FileSystemImpl::isValidPath(Core::Path const&)
Core::FileSystemImpl::isRelativePath(Core::Path const&)
Core::FileSystemImpl::getLastModificationTime(Core::Path const&, long*)
Core::FileSystemImpl::copyTimeAndAccessRights(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::_createEmptyFile(Core::Path const&)
Core::FileSystemImpl::_copyFile(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::_copyFileWithLimit(Core::Path const&, Core::Path const&, unsigned long, unsigned long&, unsigned long&)
Core::FileSystemImpl::_deleteDirectoryAndContentsRecursively(Core::Path const&)
Core::FileSystemImpl::_deleteDirectoryContentsRecursively(Core::Path const&)
Core::FileSystemImpl::_deleteRecursively(Core::Path const&, Core::FileType)
Core::FileSystemImpl::_getFileOrDirectorySize(Core::Path const&, unsigned long*)
Core::FileSystemImpl::_copyDirectoryAndContentsRecursively(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::_createDirectoryRecursively(Core::Path const&)
Core::FileSystemImpl::_createOneDirectoryIfNotExisting(Core::Path const&)
Core::FileSystemImpl::_getDirectoryFilesRecursively(std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, Core::Path const&)
Core::FileSystemImpl::_getDirectoryFiles(std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, Core::Path const&)
Core::FileSystemImpl::_getDirectoryFilesSizeRecursively(unsigned long&, Core::Path const&)
Core::FileSystemImpl::_getDirectoryFilesAllocatedSizeRecursively(unsigned long&, unsigned long&, Core::Path const&)
Core::FileSystemImpl::_isRelativePath(Core::Path const&)
Core::FileSystemImpl::_isValidPath(Core::Path const&)
Core::FileSystemImpl::_countDirectoryFiles(Core::Path const&, unsigned long*)
Core::FileSystemImpl::_readFileData(Core::Path const&, std::vector<unsigned char, std::allocator<unsigned char> >&)
Core::FileSystemImpl::_addFile(Core::FileImpl*)
Core::FileSystemImpl::_removeFile(Core::FileImpl*)
Core::FileSystemImpl::_writeOperation(Core::Path const&, Core::Result&&, std::function<void (Core::FileStorageArea*)>, unsigned long)
Core::FileSystemImpl::shouldCommit()
Core::FileSystemImpl::getCrossStorageCopyMode()
Core::FileSystemImpl::getTransactionWriteSizeLimit() const
Core::FileSystemImpl::requestFlush(std::vector<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<Core::PathBuffer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)
Core::FileSystemImpl::_endTransaction()
Core::FileSystemImpl::_createFlatFile(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::_flatFileFileExists(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::_flatFileDirectoryExists(Core::Path const&, Core::Path const&)
Core::FileSystemImpl::_flatFileIterateOverDirectory(Core::Path const&, Core::Path const&, Core::DirectoryIterationFlags, std::function<Core::Result (Core::DirectoryIterationItem const&)>)
Core::FileSystemImpl::_isDirectoryPathAFlatFile(Core::Path const&)
Core::FileSystemImpl::_copyFlatFile(Core::Path const&, Core::Path const&, std::vector<Core::ExcludedPath, std::allocator<Core::ExcludedPath> > const&, std::vector<Core::ExcludedPath, std::allocator<Core::ExcludedPath> > const&)
Core::FileSystemImpl::_flatFileDeleteFileOrDirectory(Core::Path const&, Core::Path const&, bool, bool)
Core::FileSystemImpl::_flatFileGetFileSize(Core::Path const&, Core::Path const&, unsigned long*)
Core::FileSystemImpl::notifyChangeInFileSize(long, long)
