ItemInstance::ItemInstance()
ItemInstance::ItemInstance(BlockLegacy const&, int)
ItemInstance::ItemInstance(Block const&, int, CompoundTag const*)
ItemInstance::ItemInstance(BlockLegacy const&, int, short)
ItemInstance::ItemInstance(Item const&)
ItemInstance::ItemInstance(Item const&, int)
ItemInstance::ItemInstance(Item const&, int, int)
ItemInstance::ItemInstance(Item const&, int, int, CompoundTag const*)
ItemInstance::ItemInstance(ItemInstance const&)
ItemInstance::ItemInstance(ItemStack const&)
ItemInstance::reinit(BlockLegacy const&, int)
ItemInstance::operator=(ItemInstance const&)
ItemInstance::reinit(Item const&, int, int)
ItemInstance::clone() const
ItemInstance::fromTag(CompoundTag const&)
