ItemRegistry::getItem(short)
ItemRegistry::getItem(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ItemRegistry::getItem(Block const&)
ItemRegistry::getItem(BlockLegacy const&)
ItemRegistry::getNameToItemMap[abi:cxx11]()
ItemRegistry::getItemCount()
ItemRegistry::getMaxItemID()
ItemRegistry::registerItem(SharedPtr<Item>)
ItemRegistry::unregisterItem(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ItemRegistry::lookupByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ItemRegistry::reassignOrCreateItem(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, short)
ItemRegistry::initServerData(ResourcePackManager&)
ItemRegistry::initClientData(ResourcePackManager&)
ItemRegistry::startRegistration()
ItemRegistry::shutdown()
ItemRegistry::finishedRegistration()
ItemRegistry::lookupByName(int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ItemRegistry::lookupByName(int&, int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ItemRegistry::registerAlias(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
