VanillaItems::registerItems(bool)
VanillaItems::unregisterItems()
VanillaItems::initClientData()
VanillaItems::initCreativeCategories()
VanillaItems::initCreativeItemsCallback(ActorInfoRegistry*, BlockDefinitionGroup*, bool)
