ChunkSource::createEmptyView(ChunkSource::LoadMode, bool, std::function<void (buffer_span_mut<std::shared_ptr<LevelChunk> >, buffer_span<unsigned int>)>)
ChunkSource::fireChunkLoaded(LevelChunk&)
ChunkSource::checkAndLaunchChunkGenerationTasks(bool)
ChunkSource::_hasTooManyChunksPendingDelete() const
ChunkSource::_spawnChunkGenerationTasks(int, bool)
ChunkSource::_checkAndDispatchTaskForLevelChunk(ChunkPos const&, bool)
ChunkSource::_dispatchTaskForLevelChunk(std::shared_ptr<LevelChunk>&, std::shared_ptr<ChunkViewSource>, bool)
ChunkSource::_launchGenerationTask(std::shared_ptr<LevelChunk>&, bool)
ChunkSource::_launchPostProcessingTask(std::shared_ptr<LevelChunk>&, std::shared_ptr<ChunkViewSource>, bool)
ChunkSource::_launchReplacementDataTask(std::shared_ptr<LevelChunk>&, std::shared_ptr<ChunkViewSource>, bool)
ChunkSource::_launchLightingTask(std::shared_ptr<LevelChunk>&, std::shared_ptr<ChunkViewSource>, bool)
ChunkSource::getDimension() const
ChunkSource::_loadChunkTask(LevelChunk&)
ChunkSource::_decrementTaskCountAndLaunchNewTasksFromTask()
ChunkSource::_checkForUnblockingChunks(LevelChunk&)
ChunkSource::_postProcessingTask(LevelChunk&, std::shared_ptr<ChunkViewSource>)
ChunkSource::_checkForReplacementDataTask(LevelChunk&, std::shared_ptr<ChunkViewSource>)
ChunkSource::_lightingTask(std::shared_ptr<LevelChunk>, std::shared_ptr<ChunkViewSource>)
ChunkSource::_checkSpecificLevelChunkForUnblocking(std::shared_ptr<LevelChunk>, std::shared_ptr<LevelChunkGridAreaElement<std::weak_ptr<LevelChunk> > >)
ChunkSource::_checkLevelChunkForPostProcessing(std::shared_ptr<LevelChunk>, std::shared_ptr<LevelChunkGridAreaElement<std::weak_ptr<LevelChunk> > >)
ChunkSource::_checkLevelChunkForNextStage(std::shared_ptr<LevelChunk>, std::shared_ptr<LevelChunkGridAreaElement<std::weak_ptr<LevelChunk> > >, ChunkState)
ChunkSource::_chunkAtStage(std::weak_ptr<LevelChunk>, ChunkState)
ChunkSource::getOrLoadChunk(ChunkPos const&, ChunkSource::LoadMode)
ChunkSource::ChunkSource(Dimension*, int)
ChunkSource::ChunkSource(ChunkSource&)
ChunkSource::getChunkSide() const
ChunkSource::ChunkSource(std::unique_ptr<ChunkSource, std::default_delete<ChunkSource> >)
ChunkSource::~ChunkSource()
ChunkSource::~ChunkSource()
ChunkSource::shutdown()
ChunkSource::isShutdownDone()
ChunkSource::getLevel() const
ChunkSource::getExistingChunk(ChunkPos const&)
ChunkSource::getRandomChunk(Random&)
ChunkSource::createNewChunk(ChunkPos const&, ChunkSource::LoadMode)
ChunkSource::postProcess(ChunkViewSource&)
ChunkSource::checkAndReplaceChunk(ChunkViewSource&, LevelChunk&)
ChunkSource::loadChunk(LevelChunk&, bool)
ChunkSource::hintDiscardBatchBegin()
ChunkSource::hintDiscardBatchEnd()
ChunkSource::_freeChunkGenerationGridMap(ChunkPos const&)
ChunkSource::acquireDiscarded(std::unique_ptr<LevelChunk, LevelChunkFinalDeleter>)
ChunkSource::flushPendingWrites()
ChunkSource::getParent() const
ChunkSource::getAvailableChunk(ChunkPos const&)
ChunkSource::getGeneratedChunk(ChunkPos const&)
ChunkSource::getAvailableChunkAt(BlockPos const&)
ChunkSource::getStorage() const
ChunkSource::saveLiveChunk(LevelChunk&)
ChunkSource::compact()
ChunkSource::postProcessMobsAt(BlockSource*, int, int, Random&)
ChunkSource::isWithinWorldLimit(ChunkPos const&) const
ChunkSource::getChunkMap()
