VanillaLevelChunkUpgrade::upgradeLevelChunk(LevelChunk&, BlockSource&)
VanillaLevelChunkUpgrade::fixUselessDynamicWater(LevelChunk&, BlockSource&)
VanillaLevelChunkUpgrade::convertOcelotTagToCat(CompoundTag&)
VanillaLevelChunkUpgrade::convertVillagerV1TagToV2(CompoundTag&, BlockSource&)
VanillaLevelChunkUpgrade::convertZombieVillagerV1TagToV2(CompoundTag&, BlockSource&)
VanillaLevelChunkUpgrade::convertVillagerV2TagToV1(CompoundTag&)
VanillaLevelChunkUpgrade::convertZombieVillagerV2TagToV1(CompoundTag&)
VanillaLevelChunkUpgrade::convertVillagerV1TagToV2(CompoundTag&)
VanillaLevelChunkUpgrade::getV1BehaviorFromDefinitionsList[abi:cxx11](ListTag const*)
VanillaLevelChunkUpgrade::getV1CareerFromDefinitionsList[abi:cxx11](ListTag const*)
VanillaLevelChunkUpgrade::addBiomeSpecificVillageSkins(CompoundTag&, BlockSource&)
VanillaLevelChunkUpgrade::convertZombieVillagerV1TagToV2(CompoundTag&)
