SharedAttributes::saveAttributes(BaseAttributeMap*)
SharedAttributes::_saveAttribute(AttributeInstance const&)
SharedAttributes::_saveAttributeModifier(AttributeModifier const&)
SharedAttributes::_saveAttributeBuff(TemporalAttributeBuff const&)
SharedAttributes::loadAttributes(BaseAttributeMap*, ListTag const*)
SharedAttributes::checkIsDeprecated(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
SharedAttributes::_legacyGetName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
SharedAttributes::_legacyGetInstance(BaseAttributeMap*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
SharedAttributes::_loadAttribute(AttributeInstance&, CompoundTag const*)
SharedAttributes::loadAttributeModifier(CompoundTag const*)
SharedAttributes::loadAttributeBuff(CompoundTag const*)
