Automation::AutomationClient::AutomationClient(IMinecraftApp&)
Automation::AutomationClient::onUri(ActivationUri const&)
Automation::AutomationClient::getDefaultSession()
Automation::AutomationClient::getSessionForCommand(Automation::CommandOrigin const&)
Automation::AutomationClient::createSession()
Automation::AutomationClient::isReady()
Automation::AutomationClient::send(Automation::Response const&)
Automation::AutomationClient::tick()
Automation::AutomationClient::setMaxQueueSize(unsigned long)
Automation::AutomationClient::setRequireEncryption(bool)
Automation::AutomationClient::setServerRetryTime(float)
Automation::AutomationClient::isReadyForInGameCommands()
