EnchantUtils::getBestEnchantLevel(Enchant::Type, Mob const&, EquipmentFilter)
EnchantUtils::getEquipmentSet(Mob const&, EquipmentFilter)
EnchantUtils::getEnchantLevel(Enchant::Type, ItemStackBase const&)
EnchantUtils::getRandomItemWith(Enchant::Type, Mob const&, EquipmentFilter)
EnchantUtils::hasEnchant(Enchant::Type, ItemStack const&)
EnchantUtils::getRandomItemWithMending(Mob const&)
EnchantUtils::randomlyEnchant(ItemStack&)
EnchantUtils::getLegalEnchants(Item const*)
EnchantUtils::applyEnchant(ItemStack&, Enchant::Type, int, bool)
EnchantUtils::randomlyEnchant(ItemStack&, int, int, bool)
EnchantUtils::applyEnchant(ItemStack&, ItemEnchants const&, bool)
EnchantUtils::selectEnchantments(Item const*, int, int, bool)
EnchantUtils::_convertBookCheck(ItemStack&)
EnchantUtils::randomlyEnchant(ItemInstance&)
EnchantUtils::applyEnchant(ItemInstance&, Enchant::Type, int, bool)
EnchantUtils::randomlyEnchant(ItemInstance&, int, int, bool)
EnchantUtils::applyEnchant(ItemInstance&, ItemEnchants const&, bool)
EnchantUtils::_convertBookCheck(ItemInstance&)
EnchantUtils::getLootableRandomEnchantIndex(Random&)
EnchantUtils::applyEnchant(ItemInstance&, EnchantmentInstance const&, bool)
EnchantUtils::applyEnchant(ItemStack&, EnchantmentInstance const&, bool)
EnchantUtils::removeEnchants(ItemStack&)
EnchantUtils::canEnchant(ItemStack const&, EnchantmentInstance const&, bool)
EnchantUtils::canEnchant(ItemStack const&, Enchant::Type, int, bool)
EnchantUtils::getEnchantCosts(ItemInstance const&, int)
EnchantUtils::getEnchantCosts(ItemStack const&, int)
EnchantUtils::getAvailableEnchantmentResults(Item const*, int, bool)
EnchantUtils::determineActivation(Enchant::Type)
EnchantUtils::determineCompatibility(Enchant::Type)
EnchantUtils::hasEnchant(Enchant::Type, ItemInstance const&)
EnchantUtils::getDamageReduction(ActorDamageSource const&, Mob const&)
EnchantUtils::getMeleeDamageBonus(Actor const&, Actor&)
EnchantUtils::getTotalProtectionLevels(Enchant::Type, Mob const&)
EnchantUtils::doPostHurtEffects(Mob&, Mob&)
EnchantUtils::doPostDamageEffects(Actor&, Actor&)
EnchantUtils::combineEnchantedItems(ItemStack const&, ItemStack const&, ItemStack&, bool)
EnchantUtils::isCompatibleWith(Enchant::Type, Enchant::Type)
EnchantUtils::generateRandomEnchantedItem(Item const&, int, int)
EnchantUtils::generateRandomEnchantedBook(int, int)
EnchantUtils::generateRandomEnchantedBook()
EnchantUtils::generateEnchantedBook(EnchantmentInstance const&)
EnchantUtils::generateEnchantedBook(ItemEnchants const&)
EnchantUtils::getBookcaseCount(BlockSource&, Vec3 const&)
EnchantUtils::getBookCasePositions(BlockSource&, Vec3 const&)
EnchantUtils::getEnchantingTablePositions(BlockSource&, Vec3 const&)
EnchantUtils::getRandomName[abi:cxx11]()
EnchantUtils::getEnchantNameAndLevel[abi:cxx11](Enchant::Type, int)
EnchantUtils::getEnchantmentId(Util::HashString const&)
