ColorFormat::FromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ColorFormat::NameFromFormatCode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ColorFormat::ColorFromChar(char)
ColorFormat::ColorFromColorCode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ColorFormat::IsColorCode(char)
ColorFormat::IsColorCode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ColorFormat::ColorCodeFromColor[abi:cxx11](Color const&)
ColorFormat::setColors(std::array<Color, 17ul> const&)
ColorFormat::getCurrentColors()
