CompoundTagEditHelper::CompoundTagEditHelper(Tag&)
CompoundTagEditHelper::replaceWith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<Tag, std::default_delete<Tag> >)
CompoundTagEditHelper::pushChild(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
CompoundTagEditHelper::popChild()
CompoundTagEditHelper::canPopChild()
CompoundTagEditHelper::getParent() const
CompoundTagUpdater::CompoundTagUpdater(unsigned int)
CompoundTagUpdater::update(CompoundTag&) const
CompoundTagUpdaterBuilder::CompoundTagUpdaterBuilder(CompoundTagUpdater&)
CompoundTagUpdaterBuilder::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
CompoundTagUpdaterBuilder::visit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
CompoundTagUpdaterBuilder::popVisit()
CompoundTagUpdaterBuilder::edit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (CompoundTagEditHelper&)>&&)
CompoundTagUpdaterBuilder::tryEdit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (CompoundTagEditHelper&)>&&)
CompoundTagUpdaterBuilder::remove(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
CompoundTagUpdaterBuilder::rename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
CompoundTagUpdaterContext::CompoundTagUpdaterContext()
CompoundTagUpdaterContext::addUpdater(unsigned char, unsigned char, unsigned char)
CompoundTagUpdaterContext::comparisonPredicate(std::unique_ptr<CompoundTagUpdater, std::default_delete<CompoundTagUpdater> > const&, std::unique_ptr<CompoundTagUpdater, std::default_delete<CompoundTagUpdater> > const&)
CompoundTagUpdaterContext::update(CompoundTag&, unsigned int)
CompoundTagUpdaterContext::sortUpdaters()
