PerfTimer::PerfTimer(std::thread::id)
PerfTimer::~PerfTimer()
PerfTimer::allocate(int)
PerfTimer::_roundToPower2(unsigned int)
PerfTimer::_getIdleQueue(int)
PerfTimer::allocateNodes(std::vector<PerfTimer::Node*, std::allocator<PerfTimer::Node*> >&, int)
PerfTimer::rawRelease(PerfTimer::Node*, int)
PerfTimer::push(char const*, char const*, int)
PerfTimer::pop()
PerfTimer::serialize(PerfTimer::Node const*)
PerfTimer::releaseNodeChildren(PerfTimer::Node*, int)
PerfTimer::_getMostSignificantBit(int)
PerfTimer::_getStringId(char const*)
PerfTimer::init(Core::Path const&)
PerfTimer::startEventTimerForLog(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
PerfTimer::stopEventTimerForLog(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ProfilerLite::logTimedEvent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double)
ScopedProfileTag::ScopedProfileTag(char const*, char const*, int)
ScopedProfileTag::~ScopedProfileTag()
ProfilerLite::ProfilerLite()
ProfilerLite::init(Core::Path const&)
ProfilerLite::reset()
ProfilerLite::createLog(Core::Path const&, Core::OutputFileStream&)
ProfilerLite::logToFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Core::Path, Core::OutputFileStream&)
ProfilerLite::shutdown()
ProfilerLite::closeLog(Core::OutputFileStream&)
ProfilerLite::isBenchmarkModeDone()
ProfilerLite::changeCurrentGamestateValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ProfilerLite::setTreatmentService(TreatmentService*)
ProfilerLite::setSecondaryLogFileName(Core::Path const&)
ProfilerLite::setSecondaryScreenLoadLogFileName(Core::Path const&)
ProfilerLite::setSecondaryEventLogFileName(Core::Path const&)
ProfilerLite::setCanLogToSecondaryFile(bool)
ProfilerLite::logScreenCreationEvent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double, unsigned char)
ProfilerLite::_shouldLogToSecondaryFile()
ProfilerLite::_writeHeadersIfEmpty(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Core::Path, Core::OutputFileStream&)
ProfilerLite::calculateAndSetServerTickTimes(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)
ProfilerLite::getServerTickTime() const
ProfilerLite::checkTreatmentsAndEnable(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
ProfilerLite::moveToEndOfString(char**, unsigned long&) const
ProfilerLite::openLog(Core::Path const&, Core::OutputFileStream&)
ProfilerLite::getNetworkStats(ProfilerLite::NetworkStats&, TrackerType)
ProfilerLite::getFileStats(unsigned int&, unsigned int&, double)
ProfilerLite::getDiskAccessStats(double&, double&)
ProfilerLite::_calculateRealtimeFrameData()
ProfilerLite::tick(bool, bool, int, long, long, bool)
ProfilerLite::_getProfileStringRecursive(ProfilerLite::ScopedData&, unsigned long&, unsigned long&, char*&)
ProfilerLite::getProfileString(char*, int)
