ScriptApi::WORKAROUNDS::cacheActors(entt::Registry<unsigned int>&, Level&)
ScriptApi::WORKAROUNDS::helpGetActorRegistryID(entt::Registry<unsigned int>&, ActorUniqueID const&, unsigned int&)
ScriptApi::WORKAROUNDS::helpGetActorRegistryID(entt::Registry<unsigned int>&, Actor const&, unsigned int&)
ScriptApi::WORKAROUNDS::helpRegisterActor(entt::Registry<unsigned int>&, ActorUniqueID const&, unsigned int&)
ScriptApi::WORKAROUNDS::helpRegisterActor(entt::Registry<unsigned int>&, Actor const&, unsigned int&)
ScriptApi::WORKAROUNDS::helpRegisterLevel(entt::Registry<unsigned int>&, unsigned int&)
ScriptApi::WORKAROUNDS::helpGetLevelRegistryID(entt::Registry<unsigned int>&, unsigned int&)
ScriptApi::WORKAROUNDS::helpCheckIsLevel(entt::Registry<unsigned int> const&, unsigned int)
ScriptApi::WORKAROUNDS::helpGetActorUniqueID(entt::Registry<unsigned int> const&, unsigned int, ActorUniqueID&)
ScriptApi::WORKAROUNDS::helpGetActorFromRegistyID(entt::Registry<unsigned int> const&, unsigned int, Level const&, Actor**)
ScriptApi::WORKAROUNDS::helpUpdateRegistryID(entt::Registry<unsigned int>&, unsigned int, ActorUniqueID const&)
ScriptApi::WORKAROUNDS::helpRemoveEntity(entt::Registry<unsigned int>&, Level&, unsigned int)
ScriptApi::WORKAROUNDS::helpClearEcsID(Json::Value&)
ScriptApi::WORKAROUNDS::helpPopulateEcsID(entt::Registry<unsigned int>&, Level&, Json::Value&)
