leveldb::WriteBatch::WriteBatch()
leveldb::WriteBatch::Clear()
leveldb::WriteBatch::~WriteBatch()
leveldb::WriteBatch::Handler::~Handler()
leveldb::WriteBatch::Handler::~Handler()
leveldb::WriteBatch::ApproximateSize()
leveldb::WriteBatch::Iterate(leveldb::WriteBatch::Handler*) const
leveldb::WriteBatchInternal::Count(leveldb::WriteBatch const*)
leveldb::WriteBatchInternal::SetCount(leveldb::WriteBatch*, int)
leveldb::WriteBatchInternal::Sequence(leveldb::WriteBatch const*)
leveldb::WriteBatchInternal::SetSequence(leveldb::WriteBatch*, unsigned long)
leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&)
leveldb::WriteBatch::Delete(leveldb::Slice const&)
leveldb::WriteBatchInternal::InsertInto(leveldb::WriteBatch const*, leveldb::MemTable*)
leveldb::WriteBatchInternal::SetContents(leveldb::WriteBatch*, leveldb::Slice const&)
leveldb::WriteBatchInternal::Append(leveldb::WriteBatch*, leveldb::WriteBatch const*)
