OverworldGenerator::OverworldGenerator(Dimension&, unsigned int, bool)
OverworldGenerator::_makeLayers(LevelData const&, BiomeRegistry const&)
OverworldGenerator::~OverworldGenerator()
OverworldGenerator::~OverworldGenerator()
OverworldGenerator::prepareHeights(BlockVolume&, ChunkPos const&, bool)
OverworldGenerator::_prepareHeights(BlockVolume&, ChunkPos const&, BiomeSource const&, bool)
OverworldGenerator::getHeights(float*, BiomeArea const&, int, int, int)
OverworldGenerator::buildSurfaces(OverworldGenerator::ThreadData&, BlockVolume&, LevelChunk&, ChunkPos const&)
OverworldGenerator::_prepareStructureBlueprints(ChunkPos const&, BiomeSource&)
OverworldGenerator::garbageCollectBlueprints(buffer_span<ChunkPos>)
OverworldGenerator::addHardcodedSpawnAreas(LevelChunk&)
OverworldGenerator::loadChunk(LevelChunk&, bool)
OverworldGenerator::postProcess(ChunkViewSource&)
OverworldGenerator::_fixWaterAlongEdges(LevelChunk&, BlockSource&, BlockTickingQueue&)
OverworldGenerator::postProcessMobsAt(BlockSource*, int, int, Random&)
OverworldGenerator::debugRender()
OverworldGenerator::gatherStats[abi:cxx11]()
OverworldGenerator::getFeatureTypeAt(BlockPos const&)
OverworldGenerator::findNearestFeature(StructureFeatureType, BlockPos const&, BlockPos&)
OverworldGenerator::getBiomeArea(BoundingBox const&, unsigned int) const
OverworldGenerator::findSpawnPosition() const
