BribeableDefinition::buildSchema(std::shared_ptr<JsonUtil::JsonSchemaObjectNode<JsonUtil::EmptyClass, BribeableDefinition> >&)
BribeableDefinition::addBribeItemByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
BribeableDefinition::initialize(EntityContext&, BribeableComponent&)
BribeableDefinition::deserializeData(Json::Value&)
BribeableDefinition::serializeData(Json::Value&) const
BribeableComponent::BribeableComponent()
BribeableComponent::clientBribeCheck(Actor&)
BribeableComponent::setBribed(Actor&)
BribeableComponent::resetBribe(Actor&)
BribeableComponent::getBribeTimer()
BribeableComponent::getBribeCooldown()
BribeableComponent::getInteraction(Actor&, Player&, ActorInteraction&)
BribeableComponent::addAdditionalSaveData(CompoundTag&)
BribeableComponent::readAdditionalSaveData(Actor&, CompoundTag const&, DataLoadHelper&)
