RaidBossComponent::initialize(ActorUniqueID)
RaidBossComponent::updateName(Actor&)
RaidBossComponent::_broadcastBossEvent(BossEventUpdateType, Actor&)
RaidBossComponent::updateHealthBarVisible(bool, Actor&)
RaidBossComponent::setupBossBarInfo(Actor&, std::shared_ptr<Village>)
RaidBossComponent::setRaidInProgress(bool)
RaidBossComponent::setBossBarVisibleBounds(AABB)
RaidBossComponent::getColor()
RaidBossComponent::getName[abi:cxx11]()
RaidBossComponent::getVillage()
RaidBossComponent::isWithinRange(Mob const&)
RaidBossComponent::getBossBarVisibleBounds()
RaidBossComponent::updateBossBarStats(Actor&, Raid const&)
RaidBossComponent::updatePercent(float, Actor&)
RaidBossComponent::setVillage(std::weak_ptr<Village>)
RaidBossComponent::removeBossBar(Actor&)
RaidBossComponent::sendRegistryMessages(Actor&)
RaidBossComponent::_handleRegisterPlayers(Actor&)
RaidBossComponent::getHealthPercent()
RaidBossComponent::getOwnerUniqueID()
RaidBossComponent::_sendBossEvent(BossEventUpdateType, Player&)
RaidBossComponent::registerPlayer(Player*)
RaidBossComponent::unRegisterPlayer(Player*)
RaidBossComponent::getWaveStarted()
RaidBossComponent::getRaidInProgress()
RaidBossComponent::setWaveStarted(bool)
