getTimeS()
getTimeMs()
sleepMs(int)
getUnixTime()
StopwatchNLast::StopwatchNLast(int)
Stopwatch::Stopwatch()
StopwatchNLast::~StopwatchNLast()
StopwatchNLast::~StopwatchNLast()
StopwatchNLast::stop()
Stopwatch::stop()
Stopwatch::getLast()
StopwatchNLast::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Stopwatch::getMax()
Stopwatch::reset()
Stopwatch::start()
Stopwatch::stopContinue()
Stopwatch::getTotal()
Stopwatch::getCount()
Stopwatch::tick()
Stopwatch::isReset() const
Stopwatch::printEvery(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Stopwatch::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
StopwatchHandler::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
StopwatchHandler::clear(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
StopwatchHandler::clearAll()
StopwatchHandler::print()
StopwatchHandler::printEvery(int)
RateLimiter::RateLimiter(unsigned long, std::chrono::duration<long, std::ratio<1l, 1l> >)
RateLimiter::isWithinLimit() const
RateLimiter::getNextAvailableTimePoint() const
RateLimiter::tryAddInstance()
