NavigationUtility::isInLiquid(Mob const&)
NavigationUtility::isStableDestination(Mob const&, BlockPos&)
NavigationUtility::getSurfaceY(Mob const&)
NavigationUtility::getMobScale(Mob const&)
NavigationUtility::closeToDone(Mob const&, float)
NavigationUtility::invalidPathStartStatus(Mob const&, BlockPos&)
NavigationUtility::trimPathFromSun(Mob const&)
NavigationUtility::canMoveDirectly(Mob&, Vec3 const&, Vec3 const&, int, int, int, bool)
NavigationUtility::canSwimDirectly(Mob&, Vec3 const&, Vec3 const&)
NavigationUtility::canFlyDirectly(Mob&, Vec3 const&, Vec3 const&)
NavigationUtility::canWalkDirectly(Mob&, Vec3 const&, Vec3 const&, int, int, int, bool)
NavigationUtility::canMoveDirectlyWaterBound(Mob const&, Vec3 const&, Vec3 const&)
NavigationUtility::canWalkOn(Mob&, int, int, int, int, int, int, Vec3 const&, float, float, bool)
NavigationUtility::canWalkAbove(Mob&, int, int, int, int, int, int, Vec3 const&, float, float, bool)
NavigationUtility::moveCondition(Mob const&, Block const&)
NavigationUtility::flyCondition(Mob const&, BlockSource&, int, int, int)
NavigationUtility::swimCondition(Mob const&, BlockSource&, int, int, int)
NavigationUtility::isNextNodeValid(unsigned long, Path const&)
NavigationUtility::isLastNode(unsigned long, Path const&)
NavigationUtility::isInNode(Mob const&, BlockPos const&)
NavigationUtility::isDoorBlockingPath(Mob const&, Block const&, Path const&, BlockPos const&, unsigned long)
