Core::FileSystem_generic::FileSystem_generic(Core::FileAccessType, std::shared_ptr<Core::FileStorageArea>, std::shared_ptr<Core::FlatFileManifestTracker>)
Core::FileSystem_generic::_openFile(std::unique_ptr<Core::FileImpl, std::default_delete<Core::FileImpl> >&, Core::Path const&, Core::FileOpenMode, Core::FileBufferingMode)
Core::FileSystem_generic::_iterateOverDirectory(Core::Path const&, Core::DirectoryIterationFlags, std::function<Core::Result (Core::DirectoryIterationItem const&)>)
Core::FileSystem_generic::_deleteEmptyDirectory(Core::Path const&)
Core::FileSystem_generic::_fileExists(Core::Path const&)
Core::FileSystem_generic::_fileOrDirectoryExists(Core::Path const&)
Core::FileSystem_generic::_directoryExists(Core::Path const&)
Core::FileSystem_generic::_deleteFile(Core::Path const&)
Core::FileSystem_generic::_renameDirectory(Core::Path const&, Core::Path const&)
Core::FileSystem_generic::_renameFile(Core::Path const&, Core::Path const&)
Core::FileSystem_generic::_getEntryType(Core::Path const&, Core::FileType&)
Core::FileSystem_generic::_createOneDirectory(Core::Path const&)
Core::FileSystem_generic::_renameFileOrDirectory(Core::Path const&, Core::Path const&)
Core::FileSystem_generic::_getEntryType(Core::Path const&)
Core::FileSystem_generic::_getFileSize(Core::Path const&, unsigned long*)
Core::FileSystem_generic::_getLastModificationTime(Core::Path const&, long*)
Core::FileSystem_generic::_copyTimeAndAccessRights(Core::Path const&, Core::Path const&)
