ClientPlayerEventCoordinator::sendPlayerInput(Player&, MoveInputHandler&)
ClientPlayerEventCoordinator::sendPlayerTurn(Player&, Vec2&)
ClientPlayerEventCoordinator::sendStartDestroyBlock(Player&, BlockPos const&, unsigned char&)
ClientPlayerEventCoordinator::sendPlayerDestroyedBlock(Player&, BlockLegacy const&)
ClientPlayerEventCoordinator::sendLocalPlayerDeath(IClientInstance&, LocalPlayer&)
ClientPlayerEventCoordinator::sendLocalPlayerRespawn(IClientInstance&, LocalPlayer&)
ClientPlayerEventCoordinator::sendPlayerStartRiding(Player&, Actor&)
ClientPlayerEventCoordinator::sendPlayerStopRiding(Player&, bool, bool, bool)
ClientPlayerEventCoordinator::sendPlayerCreated(LocalPlayer&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
