ItemEventCoordinator::onInventoryItemOpened(bool)
ItemEventCoordinator::onInventoryItemClosed()
ItemEventCoordinator::onItemTransferredFromContainer(ItemInstance const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ItemEventCoordinator::onItemTransferredToContainer(ItemInstance const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ItemEventCoordinator::onPreviewItemPopulatedInContainer(ItemInstance const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
ItemEventCoordinator::onInventoryLayoutSelected(int, int)
ItemEventCoordinator::onInventoryItemCraftedAutomaticallyByRecipe(ItemStack const&)
ItemEventCoordinator::onRecipeSelected(ItemStack const&)
ItemEventCoordinator::onItemSmelted(Player&, ItemDescriptor const&, ItemDescriptor const&)
ItemEventCoordinator::onItemSpawnedActor(ItemInstance const&, Actor const&)
ItemEventCoordinator::onItemModifiedActor(ItemInstance const&, Actor const&)
ItemEventCoordinator::onItemSelectedSlot(int)
ItemEventCoordinator::onItemSelected(ItemInstance const&)
