PlayerEventCoordinator::sendPlayerHurt(Player&, ActorDamageSource&)
PlayerEventCoordinator::sendPlayerMove(Player&)
PlayerEventCoordinator::sendPlayerSlide(Player&)
PlayerEventCoordinator::sendPlayerTick(Player&)
PlayerEventCoordinator::sendPlayerTeleported(Player&)
PlayerEventCoordinator::sendPlayerDestroyedBlock(Player&, int, int, int)
PlayerEventCoordinator::sendPlayerEnchantedItem(Player&, ItemStack const&, ItemEnchants const&)
PlayerEventCoordinator::sendPlayerNamedItem(Player&, ItemDescriptor const&)
PlayerEventCoordinator::sendPlayerCraftedItem(Player&, ItemInstance const&, bool, bool, bool, int, int, int, bool, bool, std::vector<short, std::allocator<short> > const&)
PlayerEventCoordinator::sendPlayerAwardAchievement(Player&, MinecraftEventing::AchievementIds)
PlayerEventCoordinator::sendPlayerPortalBuilt(Player&, AutomaticID<Dimension, int>)
PlayerEventCoordinator::sendPlayerPortalUsed(Player&, AutomaticID<Dimension, int>, AutomaticID<Dimension, int>)
PlayerEventCoordinator::sendPlayerCaravanChanged(Actor const&, int)
PlayerEventCoordinator::sendPlayerSaved(Player&)
PlayerEventCoordinator::sendPlayerItemUseInteraction(Player&, ItemInstance const&)
PlayerEventCoordinator::sendPlayerItemPlaceInteraction(Player&, ItemInstance const&)
PlayerEventCoordinator::sendPlayerItemEquipped(Player&, ItemInstance const&, int)
