BlockColorUtil::getColor(BlockColor)
BlockColorUtil::fromInt(int)
BlockColorUtil::fromItemColor(ItemColor)
BlockColorUtil::getName[abi:cxx11](BlockColor)
BlockColorUtil::getNameMixedCase[abi:cxx11](BlockColor)
BlockColorUtil::getNameSnakeCase[abi:cxx11](BlockColor)
BlockColorUtil::getRGBColor(BlockColor)
