VanillaBlockUpdater::initialize()
VanillaBlockUpdater::get()
VanillaBlockUpdater::addBaseUpdater(CompoundTagUpdaterContext&)
VanillaBlockUpdater::addUpdaters_1_10_0(CompoundTagUpdaterContext&)
VanillaBlockUpdater::addUpdaters_1_12_0(CompoundTagUpdaterContext&)
VanillaBlockUpdater::addUpdaters_1_13_0(CompoundTagUpdaterContext&)
VanillaBlockUpdater::addUpdaters_1_14_0(CompoundTagUpdaterContext&)
VanillaBlockUpdater::addUpdaters_1_15_0(CompoundTagUpdaterContext&)
VanillaBlockUpdater::destroy()
VanillaBlockUpdater::addRailUpdater_1_14_0(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CompoundTagUpdaterContext&)
