VanillaBlockStateTransformUtils::transformPortalAxis(Block const&, Rotation, Mirror)
VanillaBlockStateTransformUtils::transformDirection(Block const&, Rotation, Mirror)
VanillaBlockStateTransformUtils::transformFacingDirection(Block const&, Rotation, Mirror)
VanillaBlockStateTransformUtils::transformRailDirection(Block const&, Rotation, Mirror)
VanillaBlockStateTransformUtils::transformTorchFacingDirection(Block const&, Rotation, Mirror)
VanillaBlockStateTransformUtils::transformStandingRotation(Block const&, Rotation, Mirror)
VanillaBlockStateTransformUtils::transformStandingRotation(int, Rotation, Mirror)
VanillaBlockStateTransformUtils::transformWeirdoDirection(Block const&, Rotation, Mirror)
VanillaBlockStateTransformUtils::transformCoralDirection(Block const&, Rotation, Mirror)
VanillaBlockStateTransformUtils::transformLeverDirection(Block const&, Rotation, Mirror)
VanillaBlockStateTransformUtils::transformPillarAxis(Block const&, Rotation, Mirror)
VanillaBlockStateTransformUtils::transform(CommonDirection, Rotation, Mirror)
VanillaBlockStateTransformUtils::_mirror(CommonDirection, Mirror)
VanillaBlockStateTransformUtils::_rotate(CommonDirection, Rotation)
VanillaBlockStateTransformUtils::_rotate90(CommonDirection)
VanillaBlockStateTransformUtils::_rotate180(CommonDirection)
VanillaBlockStateTransformUtils::_rotate270(CommonDirection)
VanillaBlockStateTransformUtils::_mirrorLeftRight(CommonDirection)
VanillaBlockStateTransformUtils::_mirrorFrontBack(CommonDirection)
VanillaBlockStateTransformUtils::CommonDirectionMapping<PortalAxis> const& VanillaBlockStateTransformUtils::_getDirectionMapping<PortalAxis>()
VanillaBlockStateTransformUtils::CommonDirectionMapping<Direction::Type> const& VanillaBlockStateTransformUtils::_getDirectionMapping<Direction::Type>()
VanillaBlockStateTransformUtils::CommonDirectionMapping<Facing::Name> const& VanillaBlockStateTransformUtils::_getDirectionMapping<Facing::Name>()
VanillaBlockStateTransformUtils::CommonDirectionMapping<RailDirection> const& VanillaBlockStateTransformUtils::_getDirectionMapping<RailDirection>()
VanillaBlockStateTransformUtils::CommonDirectionMapping<TorchFacing> const& VanillaBlockStateTransformUtils::_getDirectionMapping<TorchFacing>()
VanillaBlockStateTransformUtils::CommonDirectionMapping<WeirdoDirection> const& VanillaBlockStateTransformUtils::_getDirectionMapping<WeirdoDirection>()
VanillaBlockStateTransformUtils::CommonDirectionMapping<CoralDirection> const& VanillaBlockStateTransformUtils::_getDirectionMapping<CoralDirection>()
VanillaBlockStateTransformUtils::CommonDirectionMapping<LeverDirection> const& VanillaBlockStateTransformUtils::_getDirectionMapping<LeverDirection>()
VanillaBlockStateTransformUtils::CommonDirectionMapping<PillarAxis> const& VanillaBlockStateTransformUtils::_getDirectionMapping<PillarAxis>()
