RandomPos::getPos(Vec3&, Mob&, int, int, int, SolidityCheckType)
RandomPos::generateRandomPos(Vec3&, Mob&, int, int, Vec3*, bool, bool, int, SolidityCheckType)
RandomPos::getPosTowards(Vec3&, Mob&, int, int, Vec3 const&)
RandomPos::getPosInDirection(Vec3&, Mob&, int, int, int, bool, bool, Vec3*, IntRange const&, int, SolidityCheckType)
RandomPos::generateRandomPos(Vec3&, Mob&, int, int, int, Vec3*, bool, bool, IntRange const&, int, SolidityCheckType)
RandomPos::getPosAvoid(Vec3&, Mob&, int, int, Vec3 const&)
RandomPos::getSpawnPos(BlockSource&, Random&, Vec3&, int, int, int)
RandomPos::generateRandomSpawnPos(BlockSource&, Random&, Vec3&, int, int, int, Vec3*)
RandomPos::_choosePositionOffset(Random&, BlockPos&, int, int, int, Vec3 const*)
RandomPos::snapToGround(BlockPos&, Mob&, int, IntRange const&, SolidityCheckType)
RandomPos::snapToGround(BlockPos&, int, int, int, std::function<bool (BlockPos&)>)
RandomPos::snapToGround(BlockPos&, int, int, std::function<bool (BlockPos&)>)
RandomPos::_choosePositionOffset(Random&, BlockPos&, int, int)
RandomPos::spawnSnapToGround(BlockSource&, BlockPos&, float, int)
RandomPos::_choosePositionOffset(Random&, BlockPos&, int, int, int)
