AppPlatformListener::AppPlatformListener()
AppPlatformListener::initListener(float)
AppPlatformListener::AppPlatformListener(bool)
AppPlatformListener::~AppPlatformListener()
AppPlatformListener::~AppPlatformListener()
AppPlatformListener::terminate()
