Common::getGameVersionString[abi:cxx11]()
Common::getGameVersionStringNet[abi:cxx11]()
Common::getGameSemVerString[abi:cxx11]()
Common::getServerVersionString[abi:cxx11]()
Common::getGameDevVersionString[abi:cxx11]()
Common::getGameDevGitBranchString[abi:cxx11]()
Common::getGameDevGitShaString[abi:cxx11]()
Common::getGameDevInfoString[abi:cxx11]()
Common::getBuildDateISOString[abi:cxx11]()
Common::getBuildFlavor[abi:cxx11]()
SharedConstants::isVersion(int, int, int, int)
SharedConstants::getVersionCode()
SharedConstants::getVersionCode(int, int, int, int)
