PackDependencyManager::getMissingDependencyIdentities(PackContentItem const*)
PackDependencyManager::getMissingDependencyIdentities(PackSource const*, PackManifest const&)
PackDependencyManager::packIsDependedUpon(PackManifest const&, PackManifest const&)
PackDependencyManager::hasMissingDependencies(PackContentItem const*)
PackDependencyManager::hasMissingDependencies(PackSource const*, PackManifest const&)
