Cat::Cat(ActorDefinitionGroup*, ActorDefinitionIdentifier const&)
Cat::updateEntitySpecificMolangVariables(RenderParams&)
Cat::getLieDownAmount(float)
Cat::getLieDownAmountTail(float)
Cat::getLieOnPlayer()
Cat::updateLieDownAmount()
Cat::aiStep()
Cat::getAmbientSound()
Cat::_serverAiMobStep()
Cat::onTame()
