Fish::Fish(ActorDefinitionGroup*, ActorDefinitionIdentifier const&)
Fish::normalTick()
Fish::playerTouch(Player&)
Fish::createAIGoals()
Fish::initializeComponents(Actor::InitializationMethod, VariantParameterList const&)
Fish::updateEntitySpecificMolangVariables(RenderParams&)
