TropicalFish::TropicalFish(ActorDefinitionGroup*, ActorDefinitionIdentifier const&)
TropicalFish::normalTick()
TropicalFish::playerTouch(Player&)
TropicalFish::createAIGoals()
TropicalFish::initializeComponents(Actor::InitializationMethod, VariantParameterList const&)
TropicalFish::updateEntitySpecificMolangVariables(RenderParams&)
