ScriptBlockPositionBinderComponent::ScriptBlockPositionBinderComponent()
ScriptBlockPositionBinderComponent::ScriptBlockPositionBinderComponent(BlockPos const&)
ScriptBlockPositionBinderComponent::~ScriptBlockPositionBinderComponent()
ScriptBlockPositionBinderComponent::~ScriptBlockPositionBinderComponent()
ScriptBlockPositionBinderComponent::serialize(ScriptEngine&, ScriptApi::ScriptObjectHandle const&) const
ScriptBlockPositionBinderComponent::deserialize(ScriptEngine&, ScriptApi::ScriptObjectHandle const&)
ScriptBlockPositionBinderComponent::getPosition() const
