LootItemRandomChanceWithSpecialModifierCondition::LootItemRandomChanceWithSpecialModifierCondition(float)
LootItemRandomChanceWithSpecialModifierCondition::applies(Random&, LootTableContext&)
LootItemRandomChanceWithSpecialModifierCondition::deserialize(Json::Value)
