LootItemKilledByActorCondition::LootItemKilledByActorCondition(ActorDefinitionIdentifier)
LootItemKilledByActorCondition::applies(Random&, LootTableContext&)
LootItemKilledByActorCondition::deserialize(Json::Value)
