LootItemActorHasMarkVariantCondition::LootItemActorHasMarkVariantCondition(int)
LootItemActorHasMarkVariantCondition::applies(Random&, LootTableContext&)
LootItemActorHasMarkVariantCondition::deserialize(Json::Value)
