LootItemRandomChanceWithLootingCondition::LootItemRandomChanceWithLootingCondition(float, float)
LootItemRandomChanceWithLootingCondition::applies(Random&, LootTableContext&)
LootItemRandomChanceWithLootingCondition::deserialize(Json::Value)
