LootItemRandomDifficultyChanceCondition::LootItemRandomDifficultyChanceCondition(Json::Value)
LootItemRandomDifficultyChanceCondition::applies(Random&, LootTableContext&)
LootItemRandomDifficultyChanceCondition::deserialize(Json::Value)
