ReadOnlyBinaryStream::ReadOnlyBinaryStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
ReadOnlyBinaryStream::ReadOnlyBinaryStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
BinaryStream::BinaryStream()
BinaryStream::BinaryStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
BinaryStream::BinaryStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool)
BinaryStream::BinaryStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
BinaryStream::reserve(unsigned long)
BinaryStream::reset()
BinaryStream::getAndReleaseData[abi:cxx11]()
ReadOnlyBinaryStream::read(void*, unsigned long)
BinaryStream::write(void const*, unsigned long)
ReadOnlyBinaryStream::getBool()
ReadOnlyBinaryStream::getByte()
BinaryStream::writeBool(bool)
BinaryStream::writeByte(unsigned char)
ReadOnlyBinaryStream::getSignedShort()
BinaryStream::writeSignedShort(short)
ReadOnlyBinaryStream::getUnsignedShort()
BinaryStream::writeUnsignedShort(unsigned short)
ReadOnlyBinaryStream::getSignedBigEndianInt()
BinaryStream::writeSignedBigEndianInt(int)
ReadOnlyBinaryStream::getSignedInt()
BinaryStream::writeSignedInt(int)
ReadOnlyBinaryStream::getUnsignedInt()
BinaryStream::writeUnsignedInt(unsigned int)
ReadOnlyBinaryStream::getSignedInt64()
BinaryStream::writeSignedInt64(long)
ReadOnlyBinaryStream::getUnsignedInt64()
BinaryStream::writeUnsignedInt64(unsigned long)
ReadOnlyBinaryStream::getDouble()
BinaryStream::writeDouble(double)
ReadOnlyBinaryStream::getFloat()
BinaryStream::writeFloat(float)
ReadOnlyBinaryStream::getFixedFloat(double)
ReadOnlyBinaryStream::getVarInt64()
BinaryStream::writeFixedFloat(float, double)
BinaryStream::writeVarInt64(long)
ReadOnlyBinaryStream::getNormalizedFloat()
BinaryStream::writeNormalizedFloat(float)
ReadOnlyBinaryStream::getVarInt()
ReadOnlyBinaryStream::getUnsignedVarInt()
BinaryStream::writeVarInt(int)
BinaryStream::writeUnsignedVarInt(unsigned int)
ReadOnlyBinaryStream::getUnsignedVarInt64()
BinaryStream::writeUnsignedVarInt64(unsigned long)
ReadOnlyBinaryStream::getString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
ReadOnlyBinaryStream::getString[abi:cxx11]()
ReadOnlyBinaryStream::canReadBool() const
BinaryStream::writeString(gsl::basic_string_span<char const, -1l>)
BinaryStream::writeStream(BinaryStream&)
BinaryStream::writeUnsignedChar(unsigned char)
ReadOnlyBinaryStream::getUnsignedChar()
