Util::toString(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)
Util::toString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::toWideString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::toHex(char)
Util::toHex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::fromHex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::compareNoCase(gsl::basic_string_span<char const, -1l>, gsl::basic_string_span<char const, -1l>)
Util::stringTrim(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::stringTrim(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::stringReplace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
Util::stringReplace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, buffer_span<std::pair<gsl::basic_string_span<char const, -1l>, gsl::basic_string_span<char const, -1l> > >)
Util::stringReplaceCopy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
Util::toLower[abi:cxx11](char const*)
Util::toUpper[abi:cxx11](char const*)
Util::removeInvalidFileNameCharacters(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::toLower(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::toUpper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::toLower[abi:cxx11](gsl::basic_string_span<char const, -1l> const&)
Util::toUpper[abi:cxx11](gsl::basic_string_span<char const, -1l> const&)
Util::toLowerInPlace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
Util::toUpperInPlace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
Util::format[abi:cxx11](char const*, ...)
Util::vFormat[abi:cxx11](char const*, __va_list_tag*)
Util::startsWith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::startsWith(gsl::basic_string_span<char const, -1l>, gsl::basic_string_span<char const, -1l>)
Util::normalizeLineEndings(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
Util::cp437ToUTF8(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::cp1252ToUTF8(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::stringUTF8ToUTF16(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::stringUTF16ToUTF8(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)
Util::isValidUTF8(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::u64FromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::utf8len(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::endsWith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::endsWith(gsl::basic_string_span<char const, -1l>, gsl::basic_string_span<char const, -1l>)
Util::endsWithCaseInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Util::split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)
Util::split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<bool (char)>)
Util::safeGetline(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
Util::split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool, bool, std::istream& (*)(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&))
Util::splitLines(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::istream& (*)(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&))
Util::stripBOM(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
